(() => {
  'use strict';
  const CONTENT=window.LGTReadingContent, HC=window.LGTHindiContent, N=window.LGTHindiNarratives, DAY=window.LGTReadingDay;
  if(!CONTENT||!HC||!N) throw new Error('Hindi runtime requires Hindi content and narratives.');
  const focusOrder=['general','love','career','money','wellbeing','growth'];
  const focusCopy={
    general:['जीवन की समग्र तस्वीर','अभी जीवन में किस बात को सबसे ज़्यादा ध्यान चाहिए'],
    love:['प्यार और रिश्ते','जुड़ाव, परस्परता, सीमाएँ और भावनात्मक दिशा'],
    career:['करियर और काम','काम की स्थिति, दबाव, प्रगति और अगला सार्थक कदम'],
    money:['पैसा और संसाधन','सुरक्षा, संसाधन, आदतें और व्यवहारिक निर्णय'],
    wellbeing:['भलाई और संतुलन','गति, तनाव, आराम, सीमाएँ और रिकवरी'],
    growth:['व्यक्तिगत विकास','पैटर्न, आत्मविश्वास, बदलाव और भीतर का विकास']
  };
  const activeFocus={three:null,golden:null,obstacle:null};
  const state={daily:null,ask:null,three:null,golden:null,obstacle:null};
  const $=id=>document.getElementById(id);
  const isHi=()=>document.documentElement.lang==='hi';
  const hidden=el=>!el||el.hidden||el.closest('[hidden]');
  const text=(id,v)=>{const el=$(id);if(el&&el.textContent!==v)el.textContent=v;};

  const EXACT=new Map(Object.entries({
    'DAILY GUIDANCE':'आज का मार्गदर्शन','A card for today':'आज के लिए एक कार्ड','Take a quiet moment, then choose the card you feel drawn to. The deck is already shuffled; the choice is yours.':'एक शांत पल लें, फिर उस कार्ड को चुनें जो आपका ध्यान खींचता है। डेक पहले से शफ़ल है; चुनाव आपका है।','Today’s card is already set. You can return to the same card whenever you like.':'आज का कार्ड तय हो चुका है। आप दिन भर इसी कार्ड और रीडिंग पर वापस आ सकते हैं।','Begin':'शुरू करें','Shuffling the deck':'डेक शफ़ल हो रहा है','Choose one card':'एक कार्ड चुनें','Let your eyes settle on the shuffled deck and choose the card that catches you. There is no right or wrong choice.':'शफ़ल किए गए डेक को देखें और जिस कार्ड पर ध्यान ठहर जाए उसे चुनें। यहाँ सही या गलत चुनाव नहीं है।','Your card is chosen':'आपका कार्ड चुना जा चुका है','This is your Daily Guidance card for today on this device.':'इस डिवाइस पर आज के लिए यही आपका मार्गदर्शन कार्ड रहेगा।','Reveal the card':'कार्ड खोलें','TODAY’S THEME':'आज का मुख्य संकेत','REFLECTION QUESTION':'सोचने के लिए सवाल','TODAY’S CARD':'आज का कार्ड','KEYWORDS':'मुख्य शब्द','Explore today’s card':'आज के कार्ड को अलग पहलुओं से देखें','Open the area you want to look at more closely.':'जिस क्षेत्र को अधिक स्पष्ट समझना चाहते हैं, उसे खोलें।','Work & Goals':'काम और लक्ष्य','Money & Resources':'पैसा और संसाधन','Love & Relationships':'प्यार और रिश्ते','Inner State & Balance':'भीतरी स्थिति और संतुलन','Opportunities & Watch-outs':'अवसर और सावधानियाँ','Guidance for Today':'आज के लिए दिशा','SAVE OR SHARE':'सेव या शेयर','Create a clean image of today’s reading to keep or share.':'आज की पूरी रीडिंग की एक साफ़ इमेज सेव या शेयर करें।','Save Image':'इमेज सेव करें','Share':'शेयर करें','A NEW DAILY CARD ARRIVES WITH THE NEW DAY':'नए दिन के साथ नया डेली कार्ड उपलब्ध होगा','Your next Daily Guidance will be available in':'अगली डेली रीडिंग उपलब्ध होगी','Use tarot as a tool for reflection, not a fixed prediction. Keep what feels useful and leave the rest.':'टैरो को चिंतन और दिशा के साधन की तरह लें, तय भविष्यवाणी की तरह नहीं। जो उपयोगी लगे उसे रखें, बाकी छोड़ दें।','Back to Home':'होम पर लौटें','UPRIGHT':'सीधा कार्ड',
    'ASK GANESHA':'गणेश से पूछें','Bring one question':'एक सवाल मन में लाएँ','Hold one thing in mind that you would like to see more clearly.':'एक ऐसी बात मन में रखें जिसे आप अधिक स्पष्ट समझना चाहते हैं।','What would you like to ask?':'आप क्या पूछना चाहते हैं?','Write one clear question…':'एक साफ़ सवाल लिखें…','Focus on one question at a time for a clearer reading. Your question stays on this device.':'साफ़ रीडिंग के लिए एक बार में एक ही सवाल रखें। आपका सवाल इसी डिवाइस पर रहता है।','Ask the Cards':'कार्ड से पूछें','YOUR QUESTION':'आपका सवाल','Holding your question':'आपके सवाल पर ध्यान रखा जा रहा है','Keep your question in mind, look across the shuffled deck, and choose the card that draws you in.':'सवाल को मन में रखें, शफ़ल डेक को देखें और जिस कार्ड की ओर ध्यान जाए उसे चुनें।','Take a moment with your question, then reveal the card when you are ready.':'सवाल के साथ एक पल रहें, फिर तैयार होने पर कार्ड खोलें।','SAME QUESTION · SAME CARD':'वही सवाल · वही कार्ड','You have already asked this question today, so the same card and reading are waiting for you.':'आज यह सवाल पहले पूछा जा चुका है, इसलिए वही कार्ड और वही रीडिंग आपके लिए मौजूद है।','SAME THEME · SAME READING':'वही विषय · वही रीडिंग','This is essentially the same question you asked today, so the same card and reading remain in place.':'यह आज पूछे गए सवाल का ही वही मूल विषय है, इसलिए कार्ड और रीडिंग नहीं बदलेंगे।','You can read this question again in':'इस सवाल की नई रीडिंग उपलब्ध होगी','THIS READING STAYS WITH THIS QUESTION TODAY':'आज यह रीडिंग इसी सवाल के साथ रहेगी','Reveal the Card':'कार्ड खोलें','Preparing your reading':'आपकी रीडिंग तैयार हो रही है','What should the cards focus on?':'कार्ड किस पहलू पर सबसे ज़्यादा ध्यान दें?','Your question touches more than one area. Choose the one that matters most for this reading.':'आपका सवाल एक से अधिक क्षेत्रों को छूता है। इस रीडिंग के लिए सबसे महत्वपूर्ण पहलू चुनें।','READING FOCUS':'रीडिंग का फोकस','ANSWER TO YOUR QUESTION':'आपके सवाल का सीधा जवाब','WHY THIS CARD POINTS THERE':'यह कार्ड ऐसा क्यों कह रहा है','WHAT TO KEEP IN VIEW':'साथ में क्या ध्यान रखें',"LITTLE GANESHA'S REFLECTION":'नन्हे गणेश की शांत सलाह','A QUESTION TO CARRY FORWARD':'आगे साथ रखने वाला सवाल','Ask Another Question':'दूसरा सवाल पूछें','Save a complete copy, or share a clean reading image. Your exact question is hidden from shared images unless you choose to include it.':'पूरी रीडिंग सेव करें या साफ़ इमेज शेयर करें। जब तक आप न चुनें, शेयर की गई इमेज में आपका मूल सवाल छिपा रहेगा।','Include my question in the shared image':'शेयर की गई इमेज में मेरा सवाल दिखाएँ','Off by default. The reading itself may still reveal the topic.':'डिफ़ॉल्ट रूप से बंद। रीडिंग के शब्दों से विषय का अंदाज़ा फिर भी लग सकता है।',
    'THREE-CARD READING':'तीन कार्ड की रीडिंग','Three cards, one story':'तीन कार्ड, एक जुड़ी हुई कहानी','What would you like to explore?':'आज आप किस विषय को समझना चाहते हैं?','Each focus can be completed once per local day. A focus you have already explored reopens the same cards and reading until the day changes.':'हर फोकस में दिन भर में एक नई पूर्ण रीडिंग मिलती है। जिस फोकस को आज देख चुके हैं, उस पर लौटने से वही कार्ड और वही रीडिंग खुलेगी।','Read today':'आज पढ़ा गया','Tap to revisit today’s reading':'आज की रीडिंग फिर देखने के लिए टैप करें','CURRENT FOCUS':'मौजूदा फोकस','Shuffling the full deck':'पूरा डेक शफ़ल हो रहा है','Choose a card':'कार्ड चुनें','Choose the first card for what has shaped this situation.':'पहला कार्ड चुनें—इस स्थिति को यहाँ तक लाने वाली पृष्ठभूमि के लिए।','Choose the second card for what is active now.':'दूसरा कार्ड चुनें—अभी सबसे सक्रिय स्थिति के लिए।','Choose the final card for the direction that may unfold next.':'अंतिम कार्ड चुनें—आगे खुल सकने वाली दिशा के लिए।','Past':'अतीत','Present':'वर्तमान','What May Unfold Next':'आगे क्या खुल सकता है','Chosen':'चुना गया','Your three cards are ready':'आपके तीनों कार्ड तैयार हैं','Reveal the Reading':'रीडिंग खोलें','Preparing your three-card reading':'तीन कार्ड की रीडिंग तैयार हो रही है','THE STORY THESE CARDS TELL':'तीनों कार्ड मिलकर क्या कहानी कहते हैं','THE TURNING POINT':'निर्णायक मोड़','WHAT TIES THE CARDS TOGETHER':'तीनों कार्डों को क्या जोड़ता है','WHAT TO TAKE WITH YOU':'अभी अपने साथ क्या रखें','THIS FOCUS IS COMPLETE FOR TODAY':'यह फोकस आज के लिए पूरा हो चुका है','A new reading for this focus will be available in':'इस फोकस की नई रीडिंग उपलब्ध होगी','Create a clean image of this focused three-card reading to keep or share.':'इस फोकस की तीन-कार्ड रीडिंग की साफ़ इमेज सेव या शेयर करें।',
    'THE GOLDEN PATH':'गोल्डन पाथ','Find the way forward':'आगे का रास्ता साफ़ देखें','Begin the Reading':'रीडिंग शुरू करें','Choose the first card for the ground you are standing on now.':'पहला कार्ड चुनें—अभी आप किस जमीन पर खड़े हैं, इसे देखने के लिए।','Choose the second card for what is making the path harder to see or move through.':'दूसरा कार्ड चुनें—जो रास्ते को कठिन या धुंधला बना रहा है, उसे देखने के लिए।','Choose the final card for the direction that can help you move forward.':'अंतिम कार्ड चुनें—उस दिशा के लिए जो आगे बढ़ने में मदद कर सकती है।','Where You Stand':'आप अभी कहाँ खड़े हैं','What Blocks the Path':'रास्ते में क्या अटका रहा है','The Way Forward':'आगे की दिशा','Your Golden Path cards are ready':'गोल्डन पाथ के तीनों कार्ड तैयार हैं','Reveal the Golden Path':'गोल्डन पाथ खोलें','Preparing your Golden Path reading':'गोल्डन पाथ रीडिंग तैयार हो रही है','YOUR PATH AT A GLANCE':'आपकी दिशा एक नज़र में','YOUR GOLDEN PATH':'आपका गोल्डन पाथ','WHAT TO DO NEXT':'अब क्या करें','A new Golden Path reading for this focus will be available in':'इस फोकस की नई गोल्डन पाथ रीडिंग उपलब्ध होगी','Create a clean image of your Golden Path reading to keep or share.':'गोल्डन पाथ रीडिंग की साफ़ इमेज सेव या शेयर करें।',
    'REMOVE THE OBSTACLE':'रुकावट से रास्ता निकालें','See the knot. Find the release.':'गाँठ को पहचानें, फिर उसे ढीला करने का रास्ता देखें','Where does it feel stuck?':'अभी किस क्षेत्र में बात अटकी हुई लगती है?','Choose the first card for the obstacle itself — the part of this situation that needs to be seen clearly.':'पहला कार्ड चुनें—असल रुकावट को साफ़ देखने के लिए।','Choose the second card for what keeps giving the obstacle energy or keeps the same pattern in place.':'दूसरा कार्ड चुनें—जो इस रुकावट को बार-बार ताकत दे रहा है, उसे समझने के लिए।','Choose the final card for the response, boundary, perspective, or action that can begin to loosen the knot.':'अंतिम कार्ड चुनें—उस प्रतिक्रिया, सीमा, दृष्टिकोण या कदम के लिए जो गाँठ को ढीला कर सके।','The Obstacle':'असल रुकावट','What Feeds It':'उसे क्या बनाए रखता है','What Releases It':'क्या उसे ढीला करता है','WHAT IS REALLY HAPPENING':'असल में क्या हो रहा है','THE KNOT':'मुख्य गाँठ','THE RELEASE':'गाँठ ढीली करने की दिशा','FIRST MOVES':'पहले व्यवहारिक कदम','WATCH FOR':'इस बात पर नज़र रखें','Preparing your Remove the Obstacle reading':'रुकावट वाली रीडिंग तैयार हो रही है','A new Remove the Obstacle reading for this focus will be available in':'इस फोकस की नई रुकावट रीडिंग उपलब्ध होगी',
    'General Life':'जीवन की समग्र तस्वीर','Love & Relationships':'प्यार और रिश्ते','Career & Work':'करियर और काम','Money & Resources':'पैसा और संसाधन','Well-being & Balance':'भलाई और संतुलन','Personal Growth':'व्यक्तिगत विकास',
    'A wider look at where life is asking for attention':'अभी जीवन में किस बात को सबसे ज़्यादा ध्यान चाहिए','Connection, reciprocity, boundaries, and emotional clarity':'जुड़ाव, परस्परता, सीमाएँ और भावनात्मक स्पष्टता','Work direction, pressure, progress, and meaningful next steps':'काम की दिशा, दबाव, प्रगति और अगला सार्थक कदम','Security, resources, practical choices, and financial habits':'सुरक्षा, संसाधन, व्यवहारिक चुनाव और वित्तीय आदतें','Pace, rest, emotional load, boundaries, and self-care':'गति, आराम, भावनात्मक भार, सीमाएँ और स्वयं की देखभाल','Patterns, confidence, change, and the person you are becoming':'पैटर्न, आत्मविश्वास, बदलाव और आप किस रूप में बढ़ रहे हैं',
    'The wider life story and what deserves attention now':'जीवन की बड़ी तस्वीर और अभी क्या ध्यान माँग रहा है','Connection, reciprocity, boundaries, and emotional direction':'जुड़ाव, परस्परता, सीमाएँ और भावनात्मक दिशा','Work history, present dynamics, and professional direction':'काम की पृष्ठभूमि, मौजूदा स्थिति और पेशेवर दिशा','Security, resources, habits, and practical choices':'सुरक्षा, संसाधन, आदतें और व्यवहारिक चुनाव','Pace, emotional load, rest, boundaries, and recovery':'गति, भावनात्मक भार, आराम, सीमाएँ और रिकवरी','Patterns, confidence, change, and inner development':'पैटर्न, आत्मविश्वास, बदलाव और भीतरी विकास',
    'A wider look at where life feels stuck or keeps repeating':'जीवन में कहाँ बात अटक रही है या बार-बार दोहर रही है','Connection, trust, boundaries, distance, and repeating dynamics':'जुड़ाव, भरोसा, सीमाएँ, दूरी और दोहरते पैटर्न','Stalled progress, pressure, difficult dynamics, and work direction':'रुकी हुई प्रगति, दबाव, कठिन समीकरण और काम की दिशा','Security, pressure, resource habits, and practical constraints':'सुरक्षा, दबाव, संसाधन की आदतें और व्यवहारिक सीमाएँ','Pace, emotional load, boundaries, rest, and recovery':'गति, भावनात्मक भार, सीमाएँ, आराम और रिकवरी','Beliefs, habits, fear, confidence, and patterns that limit change':'मान्यताएँ, आदतें, डर, आत्मविश्वास और बदलाव रोकने वाले पैटर्न',
    'Choose the part of life you want the cards to speak to. Then draw three cards in order: what shaped the situation, where it stands now, and what may unfold next.':'जीवन का वह क्षेत्र चुनें जिस पर आप स्पष्टता चाहते हैं। फिर तीन कार्ड चुनें—पृष्ठभूमि, अभी की वास्तविक स्थिति और आगे खुल सकने वाली दिशा के लिए।','Read the spread as a focused reflection on patterns and direction, not as a fixed prediction. Money readings are not financial advice, and well-being readings do not diagnose illness or replace professional medical care.':'इस स्प्रेड को चुने हुए विषय के पैटर्न और दिशा पर गहरी नज़र की तरह लें, तय भविष्यवाणी की तरह नहीं। पैसे की रीडिंग वित्तीय सलाह नहीं है और भलाई की रीडिंग किसी बीमारी का निदान या चिकित्सा देखभाल का विकल्प नहीं है।',
    'Choose the part of life you want to look at. Then draw three cards to see where you stand, what is blocking movement, and the direction that deserves your attention next.':'जीवन का वह क्षेत्र चुनें जिसे आप साफ़ देखना चाहते हैं। फिर तीन कार्ड चुनें—आप अभी कहाँ खड़े हैं, क्या गति रोक रहा है और किस दिशा पर आगे ध्यान देना चाहिए।','Each focus can be completed once per local day. A focus you have already explored reopens the same cards and guidance until the day changes.':'हर फोकस में दिन भर में एक नई पूर्ण रीडिंग मिलती है। आज देखे गए फोकस पर लौटने से वही कार्ड और वही मार्गदर्शन खुलेगा।','Use this reading as reflective guidance for direction and choices, not as a fixed prediction. Money readings are not financial advice, and well-being readings do not diagnose illness or replace professional medical care.':'इस रीडिंग को दिशा और चुनाव पर चिंतनात्मक मार्गदर्शन की तरह लें, तय भविष्यवाणी की तरह नहीं। पैसे की रीडिंग वित्तीय सलाह नहीं है और भलाई की रीडिंग किसी बीमारी का निदान या चिकित्सा देखभाल का विकल्प नहीं है।',
    'Choose the part of life that feels stuck. Then draw three cards to separate the obstacle itself from what keeps feeding it, and the response that can begin to loosen the pattern.':'जीवन का वह क्षेत्र चुनें जहाँ बात अटकी लगती है। फिर तीन कार्ड चुनें ताकि असल रुकावट, उसे बनाए रखने वाला पैटर्न और गाँठ ढीली करने वाली प्रतिक्रिया अलग-अलग साफ़ दिखें।','Use this reading to examine patterns, choices, and practical release points — not as a fixed prediction. Money readings are not financial advice, and well-being readings do not diagnose illness or replace professional medical care.':'इस रीडिंग से पैटर्न, चुनाव और व्यवहारिक रिलीज़-पॉइंट देखें—इसे तय भविष्यवाणी न मानें। पैसे की रीडिंग वित्तीय सलाह नहीं है और भलाई की रीडिंग किसी बीमारी का निदान या चिकित्सा देखभाल का विकल्प नहीं है।',
    'Self-image & attractiveness':'स्व-छवि और आकर्षण','How others may see you':'दूसरे आपको कैसे देख सकते हैं','Love & relationships':'प्यार और रिश्ते','Work & direction':'काम और दिशा','Money & resources':'पैसा और संसाधन','Choice & action':'चुनाव और कदम','Outlook & opportunity':'दिशा और अवसर','Inner state & growth':'भीतरी स्थिति और विकास','Spiritual & unseen':'आध्यात्मिक और अदृश्य','General reflection':'समग्र चिंतन',
    'Write one question before continuing.':'आगे बढ़ने से पहले एक सवाल लिखें।','Please shorten your question before continuing.':'आगे बढ़ने से पहले सवाल को थोड़ा छोटा करें।','Please focus on one question at a time.':'एक बार में एक ही सवाल रखें ताकि रीडिंग साफ़ रहे।','Please write a clear question using ordinary words.':'कृपया सामान्य शब्दों में एक साफ़ सवाल लिखें।','Please rephrase your question using respectful and appropriate language before continuing.':'आगे बढ़ने से पहले सवाल को सम्मानजनक और उचित भाषा में दोबारा लिखें।','This sounds like an immediate safety concern rather than a tarot question. Please reach out to someone you trust or local emergency support if you may be in danger.':'यह टैरो के सवाल से ज़्यादा तत्काल सुरक्षा की चिंता लगती है। अगर आपको अपने या किसी और के खतरे में होने का डर है, तो किसी भरोसेमंद व्यक्ति या स्थानीय आपात सहायता से तुरंत संपर्क करें।','Tarot cannot diagnose illness, pregnancy, or recovery. Please reframe this as a question about how to care for yourself or what to consider next.':'टैरो बीमारी, गर्भावस्था या उपचार के नतीजे का निदान नहीं कर सकता। सवाल को इस तरह रखें कि आप अपनी देखभाल कैसे करें या आगे क्या विचार करें।','Tarot cannot determine a court verdict or legal outcome. Please reframe this around what you can prepare, understand, or decide.':'टैरो अदालत का फैसला या कानूनी नतीजा तय नहीं कर सकता। सवाल को तैयारी, समझ या अपने निर्णय के इर्द-गिर्द रखें।','Tarot is not used here to predict lottery or gambling outcomes. Please ask about your choices, priorities, or relationship with money instead.':'यहाँ टैरो का उपयोग लॉटरी या जुए के नतीजे बताने के लिए नहीं किया जाता। इसके बजाय अपने चुनाव, प्राथमिकताओं या पैसे के साथ अपने संबंध पर सवाल पूछें।','Tarot cannot reliably predict a specific investment price or guaranteed return. Please reframe this around your risk, priorities, or decision process.':'टैरो किसी निवेश की खास कीमत या गारंटीड रिटर्न विश्वसनीय रूप से नहीं बता सकता। सवाल को जोखिम, प्राथमिकताओं या निर्णय-प्रक्रिया के इर्द-गिर्द रखें।','Tarot cannot determine when someone will die. Please reframe this around the feelings, choices, or care involved in the situation.':'टैरो यह तय नहीं कर सकता कि किसी की मृत्यु कब होगी। सवाल को स्थिति से जुड़ी भावनाओं, चुनाव या देखभाल पर केंद्रित करें।',
    'Preparing your reading image':'रीडिंग की इमेज तैयार हो रही है','Your reading image has been saved.':'रीडिंग की इमेज सेव हो गई है।','Your reading image is ready to share.':'रीडिंग की इमेज शेयर करने के लिए तैयार है।','Direct sharing is not available here, so the image was saved instead.':'यहाँ सीधे शेयर करना उपलब्ध नहीं है, इसलिए इमेज सेव कर दी गई है।','The image could not be created right now. Please try again.':'अभी इमेज नहीं बन सकी। कृपया दोबारा कोशिश करें।','Sharing was cancelled.':'शेयर रद्द कर दिया गया।'
  }));

  function replaceTextNodes(root){
    if(!root) return;
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
    const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
    nodes.forEach(n=>{const raw=n.nodeValue,trim=raw.trim();if(!trim)return;let v=EXACT.get(trim);
      if(!v){let m=trim.match(/^(\d) of 6 explored today$/);if(m)v=`आज ${m[1]} / 6 फोकस देखे गए`;
        m=trim.match(/^Choose a card · (\d)\/3$/);if(m)v=`कार्ड चुनें · ${m[1]}/3`;
      }
      if(v&&v!==trim)n.nodeValue=raw.replace(trim,v);
    });
  }
  function cardIdFromImg(img){const src=img?.getAttribute('src')||img?.src||'';const m=src.match(/(?:^|\/)(\d{2})_[^/]+\.png/i);return m?m[1]:null;}
  function cardsFrom(containerId){return [...($(containerId)?.querySelectorAll('img')||[])].map(i=>CONTENT.getCard(cardIdFromImg(i))).filter(Boolean).slice(0,3);}
  function inferFocus(mode){
    if(activeFocus[mode])return activeFocus[mode];
    const id=mode==='three'?'threeFocusCurrent':mode==='golden'?'goldenFocusCurrent':'obstacleFocusCurrent';
    const s=$(id)?.textContent||'';
    const variants={general:['General Life','जीवन की समग्र तस्वीर','ภาพรวมชีวิต'],love:['Love & Relationships','प्यार और रिश्ते','ความรัก'],career:['Career & Work','करियर और काम','การงาน'],money:['Money & Resources','पैसा और संसाधन','การเงิน'],wellbeing:['Well-being & Balance','भलाई और संतुलन','สุขภาวะ'],growth:['Personal Growth','व्यक्तिगत विकास','การเติบโต']};
    for(const [k,arr] of Object.entries(variants))if(arr.some(x=>s.includes(x)))return k;
    return 'general';
  }
  function renderFocusGrid(id){const grid=$(id);if(!grid)return;[...grid.querySelectorAll('button')].forEach((btn,i)=>{const f=focusOrder[i];if(!f)return;const [name,desc]=focusCopy[f];
    const strong=btn.querySelector('strong');if(strong)strong.textContent=name;
    const descNode=btn.querySelector('small')||btn.querySelector('p');if(descNode&&!/आज पढ़ा गया|रीडिंग फिर/.test(descNode.textContent))descNode.textContent=desc;
    replaceTextNodes(btn);
  });}
  function renderDaily(){
    const rec=window.LGTReadingEngine?.getTodayRecord?.();const card=rec?.cards?.[0]?.cardId?CONTENT.getCard(rec.cards[0].cardId):null;if(!card)return;
    if(hidden($('dailyInterpretation')))return;const p=HC.profile(card);state.daily={card};
    text('dailyCardTitle',card.title.hi);text('dailyCanonicalTitle',card.title.en);text('dailyMeaning',p.e);text('dailyReflection',p.r);
    const kw=$('dailyKeywords');if(kw)kw.replaceChildren(...p.k.map(w=>{const s=document.createElement('span');s.textContent=w;return s;}));
    const lensKeys=['workGoals','moneyResources','loveRelationships','innerBalance','opportunitiesWatchouts','guidanceToday'];
    const lensLabels=['काम और लक्ष्य','पैसा और संसाधन','प्यार और रिश्ते','भीतरी स्थिति और संतुलन','अवसर और सावधानियाँ','आज के लिए दिशा'];
    const details=[...($('dailyLensesList')?.querySelectorAll('details')||[])];details.forEach((d,i)=>{const sp=d.querySelector('summary span');const body=d.querySelector('p');if(sp)sp.textContent=lensLabels[i];if(body)body.textContent=HC.lens(card,lensKeys[i]);});
  }
  function updateCardFigures(containerId,reading){const cont=$(containerId);if(!cont||!reading)return;const figs=[...cont.querySelectorAll('figure')];figs.forEach((fig,i)=>{const pos=reading.positions[i],card=CONTENT.getCard(pos?.cardId);if(!pos||!card)return;const position=fig.querySelector('.three-result-card__position');if(position)position.textContent=pos.label;const strong=fig.querySelector('figcaption strong');if(strong)strong.textContent=card.title.hi;const small=fig.querySelector('figcaption small');if(small){small.textContent=card.title.en;small.hidden=false;}const body=fig.querySelector('figcaption p');if(body)body.textContent=pos.text;const img=fig.querySelector('img');if(img)img.alt=`टैरो कार्ड: ${card.title.hi}`;});}
  function renderThree(){const cards=cardsFrom('threeRevealedCards');if(cards.length!==3||hidden($('threeInterpretation')))return;const f=inferFocus('three'),r=N.three(cards,f);state.three={cards,focusId:f,reading:r};updateCardFigures('threeRevealedCards',r);text('threeStory',r.story);text('threeTurning',r.turningPoint);text('threePattern',r.pattern);text('threeGuidance',r.guidance);text('threeReflection',r.reflection);const cur=$('threeFocusCurrent');if(cur){const a=cur.querySelector('span'),b=cur.querySelector('strong');if(a)a.textContent='मौजूदा फोकस';if(b)b.textContent=r.focusLabel;}['अतीत','वर्तमान','आगे क्या खुल सकता है'].forEach((x,i)=>text('threeSlotLabel'+i,x));cards.forEach((c,i)=>text('threeSlotName'+i,c.title.hi));}
  function renderGolden(){const cards=cardsFrom('goldenRevealedCards');if(cards.length!==3||hidden($('goldenInterpretation')))return;const f=inferFocus('golden'),r=N.golden(cards,f);state.golden={cards,focusId:f,reading:r};updateCardFigures('goldenRevealedCards',r);text('goldenGlance',r.atGlance);text('goldenSynthesis',r.goldenPath);const ol=$('goldenActionList');if(ol)ol.replaceChildren(...r.actions.map(x=>{const li=document.createElement('li');li.textContent=x;return li;}));text('goldenReflection',r.reflection);const cur=$('goldenFocusCurrent');if(cur){const a=cur.querySelector('span'),b=cur.querySelector('strong');if(a)a.textContent='मौजूदा फोकस';if(b)b.textContent=r.focusLabel;}['आप अभी कहाँ खड़े हैं','रास्ते में क्या अटका रहा है','आगे की दिशा'].forEach((x,i)=>text('goldenSlotLabel'+i,x));cards.forEach((c,i)=>text('goldenSlotName'+i,c.title.hi));}
  function renderObstacle(){const cards=cardsFrom('obstacleRevealedCards');if(cards.length!==3||hidden($('obstacleInterpretation')))return;const f=inferFocus('obstacle'),r=N.obstacle(cards,f);state.obstacle={cards,focusId:f,reading:r};updateCardFigures('obstacleRevealedCards',r);text('obstacleGlance',r.atGlance);text('obstacleKnot',r.knot);text('obstacleRelease',r.release);const ol=$('obstacleActionList');if(ol)ol.replaceChildren(...r.actions.map(x=>{const li=document.createElement('li');li.textContent=x;return li;}));text('obstacleWatch',r.watchFor);text('obstacleReflection',r.reflection);const cur=$('obstacleFocusCurrent');if(cur){const a=cur.querySelector('span'),b=cur.querySelector('strong');if(a)a.textContent='मौजूदा फोकस';if(b)b.textContent=r.focusLabel;}['असल रुकावट','उसे क्या बनाए रखता है','क्या उसे ढीला करता है'].forEach((x,i)=>text('obstacleSlotLabel'+i,x));cards.forEach((c,i)=>text('obstacleSlotName'+i,c.title.hi));}
  function renderAsk(){if(hidden($('askInterpretation')))return;const img=$('askCardFront')||$('askInterpretation')?.querySelector('img');const id=cardIdFromImg(img);const card=CONTENT.getCard(id);if(!card)return;const question=$('askResultQuestion')?.textContent||$('askQuestionInput')?.value||'';const analysis=window.LGTQuestionAnalyzer?.analyze?.(question)||{};const r=N.ask(card,analysis,question);state.ask={card,analysis,question,reading:r};const p=HC.profile(card);text('askCardTitle',card.title.hi);text('askCanonicalTitle',card.title.en);text('askFocusResult',r.contextLabel);text('askDirectAnswer',r.direct);text('askWhyText',r.rationale);text('askConditionText',r.condition);text('askGaneshaText',r.ganesha);text('askReflection',r.reflection);const kw=$('askKeywords');if(kw)kw.replaceChildren(...p.k.map(w=>{const s=document.createElement('span');s.textContent=w;return s;}));}
  function formatRemaining(ms){let s=Math.max(0,Math.ceil(ms/1000));const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);const sec=s%60;return h?`${h} घं ${m} मि`:(m?`${m} मि ${sec} से`:`${sec} से`);}
  function countdown(){if(!isHi()||!DAY?.snapshot)return;const v=formatRemaining(DAY.snapshot().remainingMs);['dailyResetTime','askResetTime','threeResetTime','goldenResetTime','obstacleResetTime'].forEach(id=>{const el=$(id);if(el&&!hidden(el))el.textContent=v;});}
  let applying=false,pending=false;
  function apply(){if(!isHi()||applying)return;applying=true;try{observer?.disconnect();['dailyReadingView','askReadingView','threeReadingView','goldenReadingView','obstacleReadingView'].forEach(id=>replaceTextNodes($(id)));renderFocusGrid('threeFocusGrid');renderFocusGrid('goldenFocusGrid');renderFocusGrid('obstacleFocusGrid');const qi=$('askQuestionInput');if(qi)qi.placeholder='एक साफ़ सवाल लिखें…';renderDaily();renderAsk();renderThree();renderGolden();renderObstacle();countdown();}finally{applying=false;observe();}}
  function schedule(){if(!isHi()||pending)return;pending=true;requestAnimationFrame(()=>{pending=false;apply();});}
  document.addEventListener('click',e=>{if(!isHi())return;[['threeFocusGrid','three'],['goldenFocusGrid','golden'],['obstacleFocusGrid','obstacle']].forEach(([id,mode])=>{const grid=$(id),btn=e.target.closest?.(`#${id} button`);if(grid&&btn){const i=[...grid.querySelectorAll('button')].indexOf(btn);if(i>=0)activeFocus[mode]=focusOrder[i];}});},true);
  window.addEventListener('lgt:reading:interaction',()=>setTimeout(schedule,30));
  const observer=new MutationObserver(m=>{if(m.some(x=>x.attributeName==='lang'||x.type==='childList'||x.type==='characterData'))schedule();});
  function observe(){observer.observe(document.documentElement,{attributes:true,attributeFilter:['lang'],childList:true,subtree:true,characterData:true});}
  observe();
  window.setInterval(countdown,1000);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
  window.LGTHindiRuntime=Object.freeze({version:'hindi-runtime-v1',apply,getState:mode=>state[mode]||null,getFocus:mode=>inferFocus(mode),focusOrder:Object.freeze([...focusOrder])});
})();
