(() => {
  'use strict';

  const VERSION = 'journal-content-v1';
  const SUPPORTED = ['en', 'th', 'hi'];

  const COPY = {
    en: {
      eyebrow: 'PRIVATE REFLECTION ARCHIVE',
      title: 'My Path',
      intro: 'A quiet record of the readings, questions, and reflections that have travelled with you.',
      privateTitle: 'Private by design',
      privateBody: 'Your Journal stays on this device. You decide what is kept, what is reflected on, and what is deleted.',
      timeline: 'Timeline', calendar: 'Calendar', select: 'Select', cancel: 'Cancel', selectAll: 'Select all', done: 'Done',
      search: 'Search your Journal', searchPlaceholder: 'Card, focus, reflection…', filter: 'Filter', all: 'All', bookmarks: 'Bookmarked',
      entries: 'entries', reflections: 'reflections', savedMoments: 'bookmarks', thisMonth: 'This month',
      emptyTitle: 'Your path begins with the next reading',
      emptyBody: 'Completed readings can be kept here automatically, ready for you to revisit or reflect on later.',
      noMatches: 'No Journal entries match this view.',
      today: 'Today', yesterday: 'Yesterday',
      reflectionTitle: 'My Reflection',
      reflectionPrompt: 'What feels most important after sitting with this reading?',
      reflectionPlaceholder: 'Write what you noticed, what changed, or what you want to remember…',
      saveReflection: 'Save reflection', reflectionSaved: 'Reflection saved',
      savedReading: 'Saved reading', savedLanguage: 'Saved in',
      bookmark: 'Bookmark', removeBookmark: 'Remove bookmark',
      more: 'More options', deleteEntry: 'Delete entry', deleteSelected: 'Delete selected',
      deleteTitle: 'Delete this Journal entry?',
      deleteBody: 'This removes the saved reading and your reflection from this device. The original daily reading state is not changed. This cannot be undone.',
      deleteManyTitle: n => `Delete ${n} Journal entries?`,
      deleteManyBody: 'The selected saved readings and reflections will be removed from this device. Your original reading locks and daily results are not changed. This cannot be undone.',
      deleteConfirm: 'Delete', selectedCount: n => `${n} selected`,
      backHome: 'Back to Home', backJournal: 'Back to Journal',
      monthPrevious: 'Previous month', monthNext: 'Next month',
      patternEyebrow: 'A PATTERN YOU MAY WANT TO NOTICE',
      repeatedCard: (name, n) => `${name} has appeared ${n} times in this month’s saved readings.`,
      frequentFocus: (name, n) => `${name} has been your most explored focus this month, appearing in ${n} saved readings.`,
      patternNeutral: 'Your Journal is beginning to form a pattern. Keep observing before giving any single repetition too much meaning.',
      monthlyEyebrow: 'MONTHLY REFLECTION',
      monthlyTitle: month => `Your ${month} reflection`,
      monthlyPrompt: 'Looking back, what changed in the way you saw this month?',
      monthSummary: (r, f, b) => `${r} saved readings · ${f} reflections · ${b} bookmarks`,
      settingsHeading: 'Journal & Privacy',
      autoSaveTitle: 'Keep completed readings in my Journal',
      autoSaveSub: 'Store a private snapshot of completed readings on this device.',
      askQuestionTitle: 'Save exact Ask Ganesha questions',
      askQuestionSub: 'Off by default. When off, the reading is saved without the exact question text.',
      clearTitle: 'Clear Journal Data',
      clearSub: 'Delete every Journal entry and reflection from this device.',
      clearFirstTitle: 'Clear your entire Journal?',
      clearFirstBody: 'This will remove every saved Journal entry, reflection, and bookmark. Your tarot daily locks and Lucky Numbers results are not affected.',
      clearContinue: 'Continue',
      clearFinalTitle: 'Final confirmation',
      clearFinalBody: 'There is no undo. Clear all Journal data from this device?',
      clearAll: 'Clear all Journal data', clearDone: 'Journal data cleared',
      autoSaved: 'Saved quietly to your Journal',
      mode: { daily:'Daily Guidance', ask:'Ask Ganesha', three:'Three-Card Reading', golden:'The Golden Path', obstacle:'Remove the Obstacle', lucky:'Lucky Numbers' },
      focus: { general:'General Life', love:'Love & Relationships', career:'Career & Work', money:'Money & Resources', wellbeing:'Well-being & Balance', growth:'Personal Growth' },
      questionHidden: 'Exact question not stored', numbers: 'Today’s Numbers', cards: 'Cards',
      cardCount: n => `${n} card${n===1?'':'s'}`,
      dayHasEntries: n => `${n} saved ${n===1?'entry':'entries'}`,
      ariaJournal: 'Journal', ariaEntry: 'Open Journal entry'
    },
    th: {
      eyebrow: 'พื้นที่บันทึกส่วนตัว',
      title: 'เส้นทางของฉัน',
      intro: 'เก็บร่องรอยของไพ่ คำถาม และสิ่งที่คุณมองเห็นจากการอ่านแต่ละครั้งไว้ในพื้นที่ส่วนตัวของคุณ',
      privateTitle: 'เป็นส่วนตัวตั้งแต่ต้น',
      privateBody: 'บันทึกทั้งหมดอยู่บนอุปกรณ์นี้ คุณเป็นคนเลือกเองว่าจะเก็บอะไร ทบทวนอะไร และลบอะไรออก',
      timeline: 'ไทม์ไลน์', calendar: 'ปฏิทิน', select: 'เลือก', cancel: 'ยกเลิก', selectAll: 'เลือกทั้งหมด', done: 'เสร็จ',
      search: 'ค้นหาในบันทึก', searchPlaceholder: 'ชื่อไพ่ หัวข้อ สิ่งที่เขียนไว้…', filter: 'ตัวกรอง', all: 'ทั้งหมด', bookmarks: 'ที่คั่นไว้',
      entries: 'รายการ', reflections: 'บันทึกสะท้อนใจ', savedMoments: 'รายการที่คั่นไว้', thisMonth: 'เดือนนี้',
      emptyTitle: 'เส้นทางนี้จะเริ่มจากการอ่านครั้งถัดไป',
      emptyBody: 'เมื่ออ่านจบ ระบบสามารถเก็บภาพบันทึกของผลการอ่านไว้ที่นี่ เพื่อกลับมาอ่านหรือเขียนสิ่งที่คุณได้เห็นในภายหลัง',
      noMatches: 'ไม่พบบันทึกที่ตรงกับมุมมองนี้',
      today: 'วันนี้', yesterday: 'เมื่อวาน',
      reflectionTitle: 'สิ่งที่ฉันได้เห็น',
      reflectionPrompt: 'หลังจากอยู่กับคำอ่านนี้แล้ว เรื่องไหนสำคัญที่สุดสำหรับคุณ?',
      reflectionPlaceholder: 'เขียนสิ่งที่สังเกตเห็น สิ่งที่เปลี่ยนไป หรือเรื่องที่อยากจำไว้…',
      saveReflection: 'บันทึกข้อความ', reflectionSaved: 'บันทึกแล้ว',
      savedReading: 'คำอ่านที่บันทึกไว้', savedLanguage: 'ภาษาที่บันทึก',
      bookmark: 'คั่นรายการนี้', removeBookmark: 'เอาที่คั่นออก',
      more: 'ตัวเลือกเพิ่มเติม', deleteEntry: 'ลบบันทึกนี้', deleteSelected: 'ลบรายการที่เลือก',
      deleteTitle: 'ลบบันทึกรายการนี้?',
      deleteBody: 'ระบบจะลบผลการอ่านที่เก็บไว้และข้อความสะท้อนใจออกจากอุปกรณ์นี้ โดยไม่กระทบผลการอ่านหรือการล็อกผลประจำวันเดิม เมื่อลบแล้วกู้คืนไม่ได้',
      deleteManyTitle: n => `ลบบันทึก ${n} รายการ?`,
      deleteManyBody: 'ระบบจะลบผลการอ่านและข้อความสะท้อนใจของรายการที่เลือกออกจากอุปกรณ์นี้ โดยไม่กระทบผลการอ่านหรือการล็อกผลประจำวันเดิม เมื่อลบแล้วกู้คืนไม่ได้',
      deleteConfirm: 'ลบ', selectedCount: n => `เลือกแล้ว ${n} รายการ`,
      backHome: 'กลับหน้าหลัก', backJournal: 'กลับไปที่บันทึก',
      monthPrevious: 'เดือนก่อน', monthNext: 'เดือนถัดไป',
      patternEyebrow: 'รูปแบบที่น่าลองสังเกต',
      repeatedCard: (name, n) => `ไพ่ ${name} ปรากฏ ${n} ครั้งในบันทึกของเดือนนี้`,
      frequentFocus: (name, n) => `เดือนนี้คุณกลับมาดูเรื่อง “${name}” บ่อยที่สุด รวม ${n} รายการ`,
      patternNeutral: 'บันทึกของคุณกำลังเริ่มเห็นรูปแบบบางอย่าง ลองสังเกตต่อไปก่อนให้น้ำหนักกับการเกิดซ้ำเพียงอย่างเดียว',
      monthlyEyebrow: 'ทบทวนปลายเดือน',
      monthlyTitle: month => `มองย้อนกลับไปในเดือน${month}`,
      monthlyPrompt: 'เมื่อมองย้อนกลับไป วิธีที่คุณมองเดือนนี้เปลี่ยนไปตรงไหนบ้าง?',
      monthSummary: (r, f, b) => `${r} ผลการอ่าน · ${f} ข้อความสะท้อนใจ · ${b} รายการที่คั่นไว้`,
      settingsHeading: 'บันทึกและความเป็นส่วนตัว',
      autoSaveTitle: 'เก็บผลการอ่านที่จบแล้วไว้ในบันทึก',
      autoSaveSub: 'เก็บภาพบันทึกส่วนตัวของผลการอ่านไว้บนอุปกรณ์นี้โดยอัตโนมัติ',
      askQuestionTitle: 'เก็บข้อความคำถามจริงจาก “ถามพระพิฆเนศน้อย”',
      askQuestionSub: 'ปิดไว้เป็นค่าเริ่มต้น เมื่อปิด ระบบจะเก็บคำอ่านแต่ไม่เก็บข้อความคำถามตรงๆ',
      clearTitle: 'ล้างข้อมูลบันทึกทั้งหมด',
      clearSub: 'ลบผลการอ่าน ข้อความสะท้อนใจ และที่คั่นทั้งหมดออกจากอุปกรณ์นี้',
      clearFirstTitle: 'ล้างบันทึกทั้งหมด?',
      clearFirstBody: 'ผลการอ่านที่เก็บไว้ ข้อความสะท้อนใจ และที่คั่นทั้งหมดจะถูกลบ แต่การล็อกผลไพ่ประจำวันและ Lucky Numbers จะไม่เปลี่ยน',
      clearContinue: 'ดำเนินการต่อ',
      clearFinalTitle: 'ยืนยันครั้งสุดท้าย',
      clearFinalBody: 'การลบนี้ย้อนกลับไม่ได้ ต้องการล้างข้อมูล Journal ทั้งหมดจากอุปกรณ์นี้จริงๆ หรือไม่?',
      clearAll: 'ล้างข้อมูลทั้งหมด', clearDone: 'ล้างข้อมูลบันทึกแล้ว',
      autoSaved: 'เก็บไว้ในบันทึกของคุณแล้ว',
      mode: { daily:'คำแนะนำประจำวัน', ask:'ถามพระพิฆเนศน้อย', three:'เปิดไพ่สามใบ', golden:'เส้นทางสีทอง', obstacle:'คลายอุปสรรค', lucky:'เลขมงคล' },
      focus: { general:'ภาพรวมชีวิต', love:'ความรักและความสัมพันธ์', career:'การงานและอาชีพ', money:'การเงินและทรัพยากร', wellbeing:'สุขภาวะและสมดุลชีวิต', growth:'การเติบโตภายใน' },
      questionHidden: 'ไม่ได้เก็บข้อความคำถามตรงๆ', numbers: 'เลขของวันนั้น', cards: 'ไพ่',
      cardCount: n => `${n} ใบ`,
      dayHasEntries: n => `${n} รายการที่บันทึกไว้`,
      ariaJournal: 'บันทึกส่วนตัว', ariaEntry: 'เปิดบันทึกรายการนี้'
    },
    hi: {
      eyebrow: 'आपका निजी चिंतन-संग्रह',
      title: 'मेरी यात्रा',
      intro: 'आपकी रीडिंग, सवाल और उनसे निकले निजी विचार—एक शांत, निजी जगह में सुरक्षित।',
      privateTitle: 'शुरुआत से निजी',
      privateBody: 'आपका Journal इसी डिवाइस पर रहता है। क्या रखना है, किस पर लिखना है और क्या हटाना है—नियंत्रण आपके हाथ में है।',
      timeline: 'टाइमलाइन', calendar: 'कैलेंडर', select: 'चुनें', cancel: 'रद्द करें', selectAll: 'सब चुनें', done: 'हो गया',
      search: 'Journal में खोजें', searchPlaceholder: 'कार्ड, विषय, आपका नोट…', filter: 'फ़िल्टर', all: 'सभी', bookmarks: 'बुकमार्क',
      entries: 'एंट्री', reflections: 'निजी नोट', savedMoments: 'बुकमार्क', thisMonth: 'इस महीने',
      emptyTitle: 'आपकी अगली रीडिंग से यह यात्रा शुरू होगी',
      emptyBody: 'पूरी हुई रीडिंग यहाँ निजी रूप से सुरक्षित की जा सकती हैं, ताकि आप बाद में उन्हें फिर पढ़ें या अपना चिंतन लिखें।',
      noMatches: 'इस दृश्य से मेल खाने वाली कोई Journal एंट्री नहीं मिली।',
      today: 'आज', yesterday: 'कल',
      reflectionTitle: 'मेरा चिंतन',
      reflectionPrompt: 'इस रीडिंग के साथ थोड़ा समय बिताने के बाद सबसे महत्वपूर्ण बात क्या लग रही है?',
      reflectionPlaceholder: 'जो समझ आया, जो बदला, या जिसे याद रखना चाहते हैं—यहाँ लिखें…',
      saveReflection: 'नोट सेव करें', reflectionSaved: 'नोट सेव हो गया',
      savedReading: 'सेव की गई रीडिंग', savedLanguage: 'जिस भाषा में सेव हुई',
      bookmark: 'बुकमार्क करें', removeBookmark: 'बुकमार्क हटाएँ',
      more: 'और विकल्प', deleteEntry: 'एंट्री हटाएँ', deleteSelected: 'चुनी हुई एंट्री हटाएँ',
      deleteTitle: 'यह Journal एंट्री हटाएँ?',
      deleteBody: 'सेव की गई रीडिंग और आपका निजी नोट इस डिवाइस से हट जाएगा। मूल दैनिक रीडिंग या उसका लॉक नहीं बदलेगा। इसे वापस नहीं लाया जा सकेगा।',
      deleteManyTitle: n => `${n} Journal एंट्री हटाएँ?`,
      deleteManyBody: 'चुनी हुई सेव की गई रीडिंग और निजी नोट इस डिवाइस से हटेंगे। मूल रीडिंग लॉक और दैनिक नतीजे नहीं बदलेंगे। इसे वापस नहीं लाया जा सकेगा।',
      deleteConfirm: 'हटाएँ', selectedCount: n => `${n} चुनी गईं`,
      backHome: 'होम पर लौटें', backJournal: 'Journal पर लौटें',
      monthPrevious: 'पिछला महीना', monthNext: 'अगला महीना',
      patternEyebrow: 'एक पैटर्न जिस पर नज़र डालना उपयोगी हो सकता है',
      repeatedCard: (name, n) => `इस महीने की सेव की गई रीडिंग में ${name} ${n} बार आया है।`,
      frequentFocus: (name, n) => `इस महीने आपने “${name}” को सबसे ज़्यादा देखा—कुल ${n} सेव की गई रीडिंग।`,
      patternNeutral: 'आपके Journal में एक पैटर्न बनना शुरू हो रहा है। किसी एक दोहराव को बड़ा अर्थ देने से पहले थोड़ा और देखना उपयोगी होगा।',
      monthlyEyebrow: 'महीने का चिंतन',
      monthlyTitle: month => `${month} को पीछे मुड़कर देखें`,
      monthlyPrompt: 'पीछे मुड़कर देखने पर, इस महीने को देखने का आपका नज़रिया कहाँ बदला?',
      monthSummary: (r, f, b) => `${r} सेव की गई रीडिंग · ${f} निजी नोट · ${b} बुकमार्क`,
      settingsHeading: 'Journal और प्राइवेसी',
      autoSaveTitle: 'पूरी हुई रीडिंग मेरे Journal में रखें',
      autoSaveSub: 'पूरी हुई रीडिंग का निजी स्नैपशॉट इसी डिवाइस पर सेव करें।',
      askQuestionTitle: 'Ask Ganesha का पूरा सवाल सेव करें',
      askQuestionSub: 'डिफ़ॉल्ट रूप से बंद। बंद रहने पर रीडिंग सेव होगी, लेकिन आपके सवाल के सही शब्द नहीं।',
      clearTitle: 'Journal का सारा डेटा मिटाएँ',
      clearSub: 'इस डिवाइस से सभी Journal एंट्री, निजी नोट और बुकमार्क हटाएँ।',
      clearFirstTitle: 'पूरा Journal साफ़ करें?',
      clearFirstBody: 'सभी सेव की गई रीडिंग, निजी नोट और बुकमार्क हटेंगे। Tarot के दैनिक लॉक और Lucky Numbers के नतीजे प्रभावित नहीं होंगे।',
      clearContinue: 'आगे बढ़ें',
      clearFinalTitle: 'अंतिम पुष्टि',
      clearFinalBody: 'इसे वापस नहीं किया जा सकता। क्या इस डिवाइस से Journal का सारा डेटा मिटाना है?',
      clearAll: 'सारा Journal डेटा मिटाएँ', clearDone: 'Journal डेटा मिटा दिया गया',
      autoSaved: 'चुपचाप आपके Journal में सेव हो गया',
      mode: { daily:'आज का मार्गदर्शन', ask:'गणेश से पूछें', three:'तीन कार्ड की रीडिंग', golden:'गोल्डन पाथ', obstacle:'रुकावट से रास्ता', lucky:'आज के शुभ अंक' },
      focus: { general:'जीवन की समग्र तस्वीर', love:'प्यार और रिश्ते', career:'करियर और काम', money:'पैसा और संसाधन', wellbeing:'भलाई और संतुलन', growth:'व्यक्तिगत विकास' },
      questionHidden: 'सवाल के सही शब्द सेव नहीं किए गए', numbers: 'उस दिन के अंक', cards: 'कार्ड',
      cardCount: n => `${n} कार्ड`,
      dayHasEntries: n => `${n} सेव की गई एंट्री`,
      ariaJournal: 'निजी Journal', ariaEntry: 'Journal एंट्री खोलें'
    }
  };

  function language(value = document.documentElement.lang) {
    const v = String(value || '').toLowerCase().split('-')[0];
    return SUPPORTED.includes(v) ? v : 'en';
  }

  function copy(value) { return COPY[language(value)]; }

  window.LGTJournalContent = Object.freeze({ version: VERSION, language, copy });
})();
