(() => {
  'use strict';

  const VERSION = 'legal-content-v1';
  const EFFECTIVE_DATE = '2026-08-23';
  const LAST_UPDATED = '2026-08-23';
  const LEGAL_VERSION = '1.0.0';

  const SHARED = {
    en: {
      centerEyebrow:'LEGAL & PRIVACY', centerTitle:'Legal Center',
      centerIntro:'Clear rules for ownership, personal use, privacy, support, and third-party materials — written for the way Little Ganesha Tarot actually works.',
      settingsHeading:'Legal & Privacy', settingsLabel:'Legal Center', settingsSub:'Copyright, Terms of Use, Privacy and third-party notices', settingsFoot:'© 2026 Benedict Interactive · All rights reserved.',
      consentEyebrow:'LEGAL TERMS', consentTitle:'Before you continue', consentBody:'Please review the Terms of Use and Privacy Policy. By choosing Agree & Continue, you confirm that you have had the opportunity to read them and agree to the Terms to the extent permitted by applicable law.', consentAgree:'Agree & Continue', consentTerms:'Review Terms of Use', consentPrivacy:'Review Privacy Policy', consentLater:'Not now',
      backSettings:'Back to Settings', backCenter:'Back to Legal Center', home:'Back to Home', effective:'Effective', updated:'Last updated', version:'Legal version',
      centerNote:'These notices are designed to be clear and internationally usable. They do not remove rights that cannot legally be waived or limited. If translated versions differ in interpretation, the English reference text controls only to the extent permitted by applicable law.',
      principles:[
        ['PERSONAL USE','Keep and share your own readings','Personal, non-commercial screenshots and in-app Save/Share outputs are allowed.'],
        ['PRIVATE BY DESIGN','Your personal content stays local','Profile, reading state and Journal content stay on your device unless you choose to share something.'],
        ['ORIGINAL WORK','Protected materials remain protected','App code, original artwork, writing, design and curated presentation do not become open-source merely because they are viewable.'],
        ['FAIR BOUNDARIES','No overclaiming','Traditional tarot concepts, facts, public-domain material and third-party rights are not claimed as exclusive property.']
      ],
      cards:{
        copyright:['Copyright & Intellectual Property','Ownership, personal-use permission and reserved rights.','©'],
        terms:['Terms of Use','Rules for using the app, readings, Save/Share and support.','§'],
        privacy:['Privacy Policy','What stays local, what can leave by your choice, and deletion controls.','◇'],
        thirdParty:['Third-Party Notices','Fonts, payment marks, platforms and other third-party rights.','◈']
      }, docAria:'Legal document'
    },
    th: {
      centerEyebrow:'กฎหมายและความเป็นส่วนตัว', centerTitle:'ศูนย์ข้อมูลทางกฎหมาย',
      centerIntro:'ขอบเขตสิทธิ์ การใช้งานส่วนบุคคล ความเป็นส่วนตัว การสนับสนุนโปรเจกต์ และทรัพย์สินของบุคคลที่สาม อธิบายตามการทำงานจริงของ Little Ganesha Tarot',
      settingsHeading:'กฎหมายและความเป็นส่วนตัว', settingsLabel:'ศูนย์ข้อมูลทางกฎหมาย', settingsSub:'ลิขสิทธิ์ ข้อกำหนดการใช้งาน ความเป็นส่วนตัว และข้อมูลบุคคลที่สาม', settingsFoot:'© 2026 Benedict Interactive · สงวนสิทธิ์ตามกฎหมาย',
      consentEyebrow:'ข้อกำหนดทางกฎหมาย', consentTitle:'ก่อนใช้งานต่อ', consentBody:'กรุณาตรวจสอบข้อกำหนดการใช้งานและนโยบายความเป็นส่วนตัว เมื่อเลือก “ยอมรับและใช้งานต่อ” ถือว่าคุณมีโอกาสอ่านเอกสารดังกล่าวแล้ว และยอมรับข้อกำหนดเท่าที่กฎหมายอนุญาต', consentAgree:'ยอมรับและใช้งานต่อ', consentTerms:'อ่านข้อกำหนดการใช้งาน', consentPrivacy:'อ่านนโยบายความเป็นส่วนตัว', consentLater:'ไว้ภายหลัง',
      backSettings:'กลับไปหน้าตั้งค่า', backCenter:'กลับศูนย์ข้อมูลทางกฎหมาย', home:'กลับหน้าหลัก', effective:'มีผลตั้งแต่', updated:'ปรับปรุงล่าสุด', version:'เวอร์ชันเอกสาร',
      centerNote:'เอกสารชุดนี้เขียนให้ชัดเจนและรองรับการใช้งานในหลายประเทศ โดยไม่ตัดสิทธิ์ที่กฎหมายบังคับให้ผู้ใช้มีอยู่แล้ว หากฉบับแปลมีความหมายคลาดเคลื่อนจากกัน ให้ใช้ภาษาอังกฤษเป็นฉบับอ้างอิงเฉพาะเท่าที่กฎหมายอนุญาต',
      principles:[
        ['ใช้ส่วนตัวได้','เก็บและแชร์ผลการอ่านของตัวเอง','อนุญาตให้แคปหน้าจอและใช้ Save/Share เพื่อการส่วนตัวที่ไม่ใช่เชิงพาณิชย์'],
        ['ออกแบบให้เป็นส่วนตัว','ข้อมูลส่วนตัวอยู่บนอุปกรณ์','โปรไฟล์ สถานะการอ่าน และ Journal อยู่ในอุปกรณ์ เว้นแต่คุณเลือกแชร์ออกไปเอง'],
        ['งานต้นฉบับได้รับการคุ้มครอง','สิทธิ์ในตัวแอปยังคงอยู่','โค้ด งานภาพ งานเขียน การออกแบบ และการจัดวางไม่ได้กลายเป็นโอเพนซอร์สเพียงเพราะผู้ใช้มองเห็นได้'],
        ['อ้างสิทธิ์เท่าที่กฎหมายให้','ไม่อ้างครอบคลุมสิ่งที่เป็นของส่วนรวม','แนวคิด Tarot ดั้งเดิม ข้อเท็จจริง งานสาธารณสมบัติ และสิทธิ์ของบุคคลที่สามไม่ได้ถูกอ้างเป็นกรรมสิทธิ์แต่เพียงผู้เดียว']
      ],
      cards:{
        copyright:['ลิขสิทธิ์และทรัพย์สินทางปัญญา','กรรมสิทธิ์ การใช้ส่วนตัวที่อนุญาต และสิทธิ์ที่สงวนไว้','©'],
        terms:['ข้อกำหนดการใช้งาน','กติกาการใช้แอป ผลการอ่าน Save/Share และการสนับสนุน','§'],
        privacy:['นโยบายความเป็นส่วนตัว','ข้อมูลใดอยู่ในเครื่อง ข้อมูลใดออกไปเมื่อคุณเลือก และวิธีลบ','◇'],
        thirdParty:['ข้อมูลทรัพย์สินของบุคคลที่สาม','ฟอนต์ เครื่องหมายการชำระเงิน แพลตฟอร์ม และสิทธิ์ของเจ้าของแต่ละราย','◈']
      }, docAria:'เอกสารทางกฎหมาย'
    },
    hi: {
      centerEyebrow:'कानूनी जानकारी और गोपनीयता', centerTitle:'कानूनी केंद्र',
      centerIntro:'मालिकाना अधिकार, निजी उपयोग, गोपनीयता, स्वैच्छिक समर्थन और तृतीय-पक्ष सामग्री के नियम — उसी तरह लिखे गए हैं जैसे Little Ganesha Tarot वास्तव में काम करता है।',
      settingsHeading:'कानूनी जानकारी और गोपनीयता', settingsLabel:'कानूनी केंद्र', settingsSub:'कॉपीराइट, उपयोग की शर्तें, गोपनीयता और तृतीय-पक्ष सूचनाएँ', settingsFoot:'© 2026 Benedict Interactive · सर्वाधिकार सुरक्षित।',
      consentEyebrow:'कानूनी शर्तें', consentTitle:'आगे बढ़ने से पहले', consentBody:'कृपया उपयोग की शर्तें और गोपनीयता नीति देखें। “सहमत हूँ और आगे बढ़ें” चुनकर आप पुष्टि करते हैं कि आपको इन्हें पढ़ने का अवसर मिला और लागू कानून जितनी अनुमति देता है उतनी सीमा तक आप शर्तों से सहमत हैं।', consentAgree:'सहमत हूँ और आगे बढ़ें', consentTerms:'उपयोग की शर्तें देखें', consentPrivacy:'गोपनीयता नीति देखें', consentLater:'अभी नहीं',
      backSettings:'सेटिंग्स पर लौटें', backCenter:'कानूनी केंद्र पर लौटें', home:'होम पर लौटें', effective:'प्रभावी तिथि', updated:'अंतिम अपडेट', version:'कानूनी संस्करण',
      centerNote:'इन दस्तावेज़ों को स्पष्ट और अंतरराष्ट्रीय उपयोग के योग्य बनाया गया है। ये उन अधिकारों को सीमित नहीं करते जिन्हें लागू कानून के तहत छोड़ा या सीमित नहीं किया जा सकता। अनुवादों में अर्थ का अंतर होने पर, लागू कानून जितनी अनुमति देता है उतनी सीमा तक अंग्रेज़ी संदर्भ-पाठ माना जाएगा।',
      principles:[
        ['व्यक्तिगत उपयोग','अपनी रीडिंग सेव और शेयर करें','व्यक्तिगत, गैर-व्यावसायिक स्क्रीनशॉट और ऐप के Save/Share आउटपुट की अनुमति है।'],
        ['गोपनीयता को ध्यान में रखकर बनाया गया','आपकी निजी सामग्री डिवाइस पर रहती है','प्रोफ़ाइल, रीडिंग स्टेट और जर्नल डिवाइस पर रहते हैं, जब तक आप स्वयं कुछ शेयर न करें।'],
        ['मौलिक कार्य','संरक्षित सामग्री संरक्षित रहती है','ऐप कोड, मौलिक आर्टवर्क, लेखन, डिज़ाइन और चुनी हुई प्रस्तुति केवल दिखाई देने भर से ओपन-सोर्स नहीं हो जाती।'],
        ['उचित सीमा','अधिकारों का जरूरत से ज़्यादा दावा नहीं','पारंपरिक टैरो अवधारणाएँ, तथ्य, पब्लिक-डोमेन सामग्री और तृतीय-पक्ष अधिकारों पर विशिष्ट मालिकाना दावा नहीं किया जाता।']
      ],
      cards:{
        copyright:['कॉपीराइट और बौद्धिक संपदा','मालिकाना अधिकार, व्यक्तिगत उपयोग की अनुमति और सुरक्षित अधिकार।','©'],
        terms:['उपयोग की शर्तें','ऐप, रीडिंग, Save/Share और समर्थन के नियम।','§'],
        privacy:['गोपनीयता नीति','क्या डिवाइस पर रहता है, आपकी पसंद से क्या बाहर जा सकता है और क्या हटाया जा सकता है।','◇'],
        thirdParty:['तृतीय-पक्ष सूचनाएँ','फ़ॉन्ट, भुगतान चिह्न, प्लेटफ़ॉर्म और अन्य तृतीय-पक्ष अधिकार।','◈']
      }, docAria:'कानूनी दस्तावेज़'
    }
  };

  const DOCS = {
    copyright: {
      en:{title:'Copyright & Intellectual Property',subtitle:'Ownership, permitted personal use, and reserved rights.',sections:[
        ['1. Scope and rights holder',[`© 2026 Benedict Interactive. All rights reserved. “Benedict Interactive” refers to the studio/project identity under which Little Ganesha Tarot — The Golden Path is developed and published, together with the applicable legal rights holder or rights holders operating under that name.`,`Except for identified third-party or public-domain material, protectable original material in Little Ganesha Tarot is reserved to its applicable rights holder to the fullest extent permitted by law.`]],
        ['2. Protected original materials',[`Protected materials may include original source code and software components; software structure and documentation; user-interface and interaction design; Little Ganesha tarot artwork and visual compositions; graphics, animation and audiovisual presentation; original tarot interpretations, educational and editorial writing; localization; original selection, coordination and arrangement of content; reading presentation flows; brand assets; icons; and original promotional or publishing materials.`]],
        ['3. Rights we do not claim',[`This notice does not claim exclusive ownership over tarot as a general concept, traditional tarot terminology or structures, historical facts, ideas, principles, methods, procedures, systems, public-domain material, or third-party works and marks. Protection is asserted only where applicable law recognizes a protectable original contribution or other legal right.`]],
        ['4. Personal screenshots, Save and Share',[`You may make screenshots of your own use of the app and use the app’s Save/Share features for ordinary personal, non-commercial purposes. You may share your own reading output with friends or on a personal social account, provided you do not falsely imply endorsement, sell the material, mass-distribute the deck or underlying assets, or remove existing ownership notices to misrepresent origin.`,`This limited permission covers the personal output you receive. It does not transfer ownership of the underlying card art, templates, software, design system, reading library or source assets. The fact that the app does not technically block screenshots grants no additional rights.`]],
        ['5. Uses requiring permission',[`Unless expressly permitted by applicable law or authorized in writing, protected material may not be copied, republished, translated, adapted, redistributed, sold, sublicensed, commercially exploited, mirrored, systematically extracted, scraped, bulk-downloaded, incorporated into another product, used to reproduce a competing deck or interface, or used to create derivative commercial products.`,`Automated extraction for dataset creation, model training, fine-tuning, model evaluation, retrieval corpora or similar machine-learning uses is not authorized except where a non-waivable legal right applies or written permission has been granted.`]],
        ['6. Software and technical protection',[`No source-code license is granted merely because code or assets are technically accessible. Reverse engineering, decompilation, disassembly, circumvention of access or security controls, automated harvesting and extraction are prohibited to the extent permitted by law, subject to mandatory interoperability, security-research or other statutory rights that cannot lawfully be excluded.`]],
        ['7. User-created content',[`Questions, reflections and notes that you personally write remain your content, subject to applicable law. Benedict Interactive does not claim ownership of them merely because they are entered into the app. This does not give you ownership of surrounding app artwork, reading text, software or other protected materials.`]],
        ['8. AI-assisted materials',[`Some production materials may have been developed with digital or generative tools. No claim is made beyond rights recognized by applicable law. Where protectable, rights are asserted in human-authored or human-directed contributions such as source code, writing, creative direction, selection, arrangement, editing, compositing, adaptation, branding and final protectable expression.`]],
        ['9. Brand and source identifiers',[`Little Ganesha Tarot, The Golden Path, Benedict Interactive, associated logos, trade dress and other source-identifying elements may be protected by copyright, trademark, passing-off, unfair-competition or related laws to the extent applicable. No permission is granted to use them in a way that falsely suggests sponsorship, affiliation, origin or endorsement.`]],
        ['10. Reservation of rights',[`All rights not expressly granted are reserved. A failure or delay in enforcing a right does not by itself waive that right. Nothing in this notice restricts fair use, fair dealing, quotation, statutory exceptions, interoperability rights, consumer rights or any other rights that applicable law makes non-waivable.`]],
        ['11. Permissions and licensing requests',[`Requests for commercial licensing, publishing, reproduction, partnerships or other permission should be submitted through an official Benedict Interactive contact channel when one is published. Permission for one use does not imply permission for another use, and any permission may be subject to separate written terms.`]]
      ]},
      th:{title:'ลิขสิทธิ์และทรัพย์สินทางปัญญา',subtitle:'กรรมสิทธิ์ การใช้งานส่วนตัวที่อนุญาต และสิทธิ์ที่สงวนไว้',sections:[
        ['1. ขอบเขตและผู้ถือสิทธิ์',[`© 2026 Benedict Interactive สงวนสิทธิ์ตามกฎหมาย คำว่า “Benedict Interactive” ในเอกสารนี้หมายถึงชื่อสตูดิโอ/โปรเจกต์ที่ใช้พัฒนาและเผยแพร่ Little Ganesha Tarot — The Golden Path รวมถึงผู้ถือสิทธิ์ตามกฎหมายที่เกี่ยวข้องซึ่งดำเนินงานภายใต้ชื่อนี้`,`เว้นแต่วัสดุของบุคคลที่สามหรือสิ่งที่เป็นสาธารณสมบัติซึ่งระบุไว้ต่างหาก งานต้นฉบับที่กฎหมายให้ความคุ้มครองใน Little Ganesha Tarot ถูกสงวนสิทธิ์โดยผู้ถือสิทธิ์ที่เกี่ยวข้องอย่างเต็มที่เท่าที่กฎหมายอนุญาต`]],
        ['2. งานต้นฉบับที่ได้รับการคุ้มครอง',[`อาจรวมถึงซอร์สโค้ดและส่วนประกอบซอฟต์แวร์ โครงสร้างและเอกสารซอฟต์แวร์ การออกแบบ UI/UX งานภาพไพ่ Little Ganesha และองค์ประกอบภาพ กราฟิก แอนิเมชัน งานภาพและเสียง คำอ่าน Tarot บทความและเนื้อหาความรู้ งานแปลและการปรับภาษา การคัดเลือกและจัดเรียงเนื้อหา รูปแบบการนำเสนอคำอ่าน สินทรัพย์แบรนด์ ไอคอน และสื่อประชาสัมพันธ์หรือสิ่งพิมพ์ต้นฉบับ`]],
        ['3. สิ่งที่เราไม่ได้อ้างเป็นสิทธิ์เฉพาะ',[`เอกสารนี้ไม่ได้อ้างกรรมสิทธิ์แต่เพียงผู้เดียวเหนือแนวคิด Tarot โดยทั่วไป คำศัพท์หรือโครงสร้างดั้งเดิม ข้อเท็จจริงทางประวัติศาสตร์ แนวคิด หลักการ วิธีการ ขั้นตอน ระบบ สิ่งที่เป็นสาธารณสมบัติ หรืองานและเครื่องหมายของบุคคลที่สาม เราอ้างสิทธิ์เฉพาะส่วนที่กฎหมายรับรองว่าเป็นผลงานต้นฉบับหรือสิทธิ์ที่ได้รับความคุ้มครอง`]],
        ['4. การแคปหน้าจอ การบันทึก และการแชร์เพื่อใช้ส่วนตัว',[`คุณสามารถแคปหน้าจอจากการใช้งานของตัวเอง และใช้ฟังก์ชัน Save/Share เพื่อการส่วนตัวที่ไม่ใช่เชิงพาณิชย์ได้ รวมถึงแชร์ผลการอ่านของตัวเองกับเพื่อนหรือบัญชีโซเชียลส่วนตัว ตราบใดที่ไม่ทำให้ผู้อื่นเข้าใจผิดว่าได้รับการรับรองจาก Benedict Interactive ไม่นำไปขาย ไม่เผยแพร่สำรับหรือสินทรัพย์ต้นฉบับจำนวนมาก และไม่ลบข้อความแสดงสิทธิ์เพื่อบิดเบือนแหล่งที่มา`,`สิทธิ์นี้ครอบคลุมผลลัพธ์ส่วนตัวที่คุณได้รับ ไม่ได้โอนกรรมสิทธิ์ในงานภาพไพ่ เทมเพลต ซอฟต์แวร์ ระบบออกแบบ คลังคำอ่าน หรือไฟล์ต้นฉบับ การที่แอปไม่ได้บล็อกการแคปหน้าจอทางเทคนิคไม่ได้หมายความว่ามีการให้สิทธิ์เพิ่มเติม`]],
        ['5. การใช้งานที่ต้องได้รับอนุญาต',[`เว้นแต่กฎหมายอนุญาตหรือได้รับอนุญาตเป็นลายลักษณ์อักษร ห้ามทำซ้ำ ตีพิมพ์ซ้ำ แปล ดัดแปลง แจกจ่าย ขาย อนุญาตช่วง ใช้เชิงพาณิชย์ ทำ mirror ดึงข้อมูลอย่างเป็นระบบ scrape ดาวน์โหลดจำนวนมาก รวมเข้าในสินค้า/บริการอื่น ทำสำรับหรือ UI ที่แข่งขัน หรือสร้างผลิตภัณฑ์ดัดแปลงเพื่อการค้า`,`ไม่อนุญาตให้ดึงข้อมูลอัตโนมัติเพื่อสร้าง dataset ฝึก/fine-tune โมเดล ประเมินโมเดล สร้าง retrieval corpus หรือใช้ด้าน machine learning ในลักษณะใกล้เคียง เว้นแต่เป็นสิทธิ์ตามกฎหมายที่ไม่อาจสละได้หรือได้รับอนุญาตเป็นลายลักษณ์อักษร`]],
        ['6. ซอฟต์แวร์และการคุ้มครองทางเทคนิค',[`การที่ซอร์สโค้ดหรือไฟล์เข้าถึงได้ทางเทคนิคไม่ได้หมายความว่าได้รับสิทธิ์ใช้งานซอร์สโค้ด ห้าม reverse engineer, decompile, disassemble, หลีกเลี่ยงมาตรการควบคุม/ความปลอดภัย หรือดึงข้อมูลอัตโนมัติ เท่าที่กฎหมายอนุญาต โดยไม่ตัดสิทธิ์ interoperability งานวิจัยความปลอดภัย หรือข้อยกเว้นบังคับตามกฎหมาย`]],
        ['7. เนื้อหาที่ผู้ใช้เขียนเอง',[`คำถาม ข้อความสะท้อนใจ และบันทึกที่คุณเขียนเองยังคงเป็นเนื้อหาของคุณตามกฎหมาย Benedict Interactive ไม่อ้างกรรมสิทธิ์เพียงเพราะคุณพิมพ์ข้อมูลดังกล่าวลงในแอป แต่ไม่ได้ทำให้คุณเป็นเจ้าของงานภาพ คำอ่าน ซอฟต์แวร์ หรือเนื้อหาที่ได้รับการคุ้มครองรอบๆ เนื้อหาของคุณ`]],
        ['8. งานที่ใช้ AI หรือเครื่องมือดิจิทัลช่วย',[`วัสดุบางส่วนอาจใช้เครื่องมือดิจิทัลหรือ generative tools ช่วยผลิต เราไม่อ้างสิทธิ์เกินขอบเขตที่กฎหมายรับรอง ในส่วนที่กฎหมายคุ้มครอง เราสงวนสิทธิ์ในผลงานของมนุษย์และการกำกับสร้างสรรค์ เช่น ซอร์สโค้ด งานเขียน ทิศทางศิลป์ การคัดเลือก การจัดวาง การแก้ไข การประกอบภาพ การดัดแปลง แบรนด์ และรูปแบบการแสดงออกขั้นสุดท้าย`]],
        ['9. ชื่อแบรนด์และเครื่องหมายที่บอกแหล่งที่มา',[`Little Ganesha Tarot, The Golden Path, Benedict Interactive โลโก้ ลักษณะการนำเสนอแบรนด์ และองค์ประกอบที่ใช้ระบุแหล่งที่มาอาจได้รับความคุ้มครองตามกฎหมายที่เกี่ยวข้อง ห้ามนำไปใช้ในลักษณะที่ทำให้เข้าใจผิดว่าได้รับการสนับสนุน มีความเกี่ยวข้อง หรือได้รับอนุญาตจากเรา`]],
        ['10. การสงวนสิทธิ์',[`สิทธิ์ที่ไม่ได้ให้ไว้โดยชัดแจ้งถือว่าสงวนไว้ การไม่บังคับใช้สิทธิ์ในบางครั้งไม่ได้หมายถึงการสละสิทธิ์ เอกสารนี้ไม่จำกัด fair use, fair dealing, การอ้างอิง ข้อยกเว้นตามกฎหมาย สิทธิ์ interoperability สิทธิ์ผู้บริโภค หรือสิทธิ์อื่นที่กฎหมายกำหนดว่าไม่อาจสละหรือลดทอนได้`]],
        ['11. การขออนุญาตและการให้สิทธิ์ใช้งาน',[`คำขอใช้เชิงพาณิชย์ การตีพิมพ์ การทำซ้ำ ความร่วมมือ หรือการขออนุญาตอื่น ควรส่งผ่านช่องทางติดต่อทางการของ Benedict Interactive เมื่อมีการประกาศใช้งาน การอนุญาตสำหรับกรณีหนึ่งไม่ได้หมายถึงอนุญาตกรณีอื่น และอาจอยู่ภายใต้ข้อตกลงเป็นลายลักษณ์อักษรเพิ่มเติม`]]
      ]},
      hi:{title:'कॉपीराइट और बौद्धिक संपदा',subtitle:'मालिकाना अधिकार, अनुमत व्यक्तिगत उपयोग और सुरक्षित अधिकार।',sections:[
        ['1. दायरा और अधिकार-धारक',[`© 2026 Benedict Interactive. सर्वाधिकार सुरक्षित। “Benedict Interactive” उस स्टूडियो/प्रोजेक्ट पहचान को दर्शाता है जिसके अंतर्गत Little Ganesha Tarot — The Golden Path विकसित और प्रकाशित होता है, साथ ही उस नाम के अंतर्गत काम करने वाले लागू कानूनी अधिकार-धारक को भी।`,`पहचानी गई third-party या public-domain सामग्री को छोड़कर, कानून द्वारा संरक्षित मौलिक सामग्री संबंधित अधिकार-धारक के लिए लागू कानून की अधिकतम सीमा तक सुरक्षित रहती है।`]],
        ['2. संरक्षित मौलिक सामग्री',[`इसमें मौलिक source code, software components/structure/documentation, UI/UX design, Little Ganesha tarot artwork, visual compositions, graphics, animation, audiovisual presentation, मौलिक tarot interpretations, educational/editorial writing, localization, content selection/arrangement, reading presentation flows, brand assets, icons और promotional/publishing material शामिल हो सकते हैं।`]],
        ['3. जिन चीज़ों पर विशिष्ट स्वामित्व का दावा नहीं',[`सामान्य tarot अवधारणा, पारंपरिक terminology/structure, historical facts, ideas, principles, methods, procedures, systems, public-domain material या third-party works/marks पर विशिष्ट स्वामित्व का दावा नहीं किया जाता। अधिकार वहीं दावा किए जाते हैं जहाँ कानून मौलिक योगदान या अन्य कानूनी अधिकार को संरक्षण देता है।`]],
        ['4. व्यक्तिगत screenshots, Save और Share',[`आप अपने उपयोग के screenshots ले सकते हैं और app के Save/Share output का व्यक्तिगत, गैर-व्यावसायिक उपयोग कर सकते हैं। अपनी reading मित्रों या personal social account पर share करना भी अनुमत है, बशर्ते false endorsement न दिखाया जाए, सामग्री न बेची जाए, deck/assets का mass distribution न हो और source गलत दिखाने के लिए ownership notices न हटाए जाएँ।`,`यह सीमित अनुमति personal output तक है; card art, templates, software, design system, reading library या source assets का ownership transfer नहीं होता। Screenshot blocking न होना अतिरिक्त अधिकार की अनुमति नहीं देता।`]],
        ['5. अनुमति आवश्यक उपयोग',[`लिखित अनुमति या लागू कानूनी exception के बिना protected material की copying, republication, translation, adaptation, redistribution, sale, sublicensing, commercial exploitation, mirroring, systematic extraction, scraping, bulk download, competing deck/interface reproduction या commercial derivative product creation की अनुमति नहीं है।`,`Dataset creation, model training/fine-tuning/evaluation, retrieval corpus या समान ML use के लिए automated extraction की अनुमति नहीं है, सिवाय non-waivable legal right या लिखित अनुमति के।`]],
        ['6. Software और technical protection',[`Code/assets का technically accessible होना source-code license नहीं देता। Applicable law की सीमा तक reverse engineering, decompilation, disassembly, access/security controls को bypass करना और automated harvesting प्रतिबंधित है, mandatory interoperability/security-research rights को छोड़कर।`]],
        ['7. User-created content',[`आपके अपने questions, reflections और notes आपके content बने रहते हैं। केवल app में दर्ज करने से Benedict Interactive उनका ownership दावा नहीं करता; इससे आसपास के artwork, reading text या software पर आपका ownership नहीं बनता।`]],
        ['8. AI-assisted materials',[`कुछ production material digital या generative tools की सहायता से विकसित हो सकता है। कानून से अधिक अधिकार का दावा नहीं किया जाता। जहाँ protection उपलब्ध है, वहाँ human-authored/human-directed source code, writing, creative direction, selection, arrangement, editing, compositing, adaptation, branding और final protectable expression पर अधिकार सुरक्षित किए जाते हैं।`]],
        ['9. Brand और source identifiers',[`Little Ganesha Tarot, The Golden Path, Benedict Interactive, logos, trade dress और अन्य source-identifying elements लागू सीमा तक संबंधित laws से protected हो सकते हैं। False sponsorship, affiliation, origin या endorsement का संकेत देने वाला उपयोग अनुमत नहीं है।`]],
        ['10. अधिकार सुरक्षित',[`जो अधिकार स्पष्ट रूप से नहीं दिए गए वे सुरक्षित हैं। Enforcement में delay अपने-आप waiver नहीं है। Fair use/fair dealing, quotation, statutory exceptions, interoperability, consumer rights और non-waivable rights सुरक्षित रहते हैं।`]],
        ['11. Permission और licensing requests',[`Commercial licensing, publishing, reproduction, partnership या अन्य permission request official Benedict Interactive contact channel उपलब्ध होने पर वहीं भेजें। एक use के लिए permission किसी दूसरे use की permission नहीं मानी जाएगी और अलग written terms लागू हो सकती हैं।`]]
      ]}
    },

    terms: {
      en:{title:'Terms of Use',subtitle:'Rules for accessing and using Little Ganesha Tarot.',sections:[
        ['1. Agreement to these Terms',[`By selecting “Agree & Continue” when the legal notice is presented, or by continuing to use Little Ganesha Tarot — The Golden Path after that acceptance, you agree to these Terms to the extent a binding agreement may be formed under applicable law. If you do not agree, do not continue using the app. Mandatory consumer rights and non-waivable protections remain in effect.`,`These Terms cover the app, local features, reading outputs, support screens and protected materials. Separate third-party terms may apply when you use an external service.`]],
        ['2. Nature of the service',[`Little Ganesha Tarot is a reflective tarot and self-exploration experience. Tarot readings, Lucky Numbers and related material are not guaranteed predictions and should not be treated as factual certainty about future events or another person’s private thoughts.`,`The app does not provide medical diagnosis/treatment, legal advice, financial or investment advice, gambling advice, emergency services or other regulated professional services.`]],
        ['3. Limited personal-use license',[`You receive a limited, revocable, non-exclusive, non-transferable permission to access and use the app for ordinary personal purposes. This is a right to use the service, not a transfer of ownership in software, artwork, writing or other protected material.`]],
        ['4. Screenshots and personal sharing',[`You may take screenshots of your own app experience and use in-app Save/Share outputs for personal, non-commercial use. Ordinary sharing of your own reading on a personal social account is permitted.`,`This does not allow publishing the full deck as an asset archive, redistributing clean card files, selling products based primarily on copied app text/art, removing branding to misrepresent authorship, using protected content in paid products/courses, or mass-copying the app. Absence of screenshot blocking is not consent to those uses.`]],
        ['5. Prohibited conduct',[`You must not violate law or third-party rights; interfere with operation/security; impersonate Benedict Interactive; distribute malware; exploit vulnerabilities without lawful authorization; scrape/bulk-extract protected content; bypass technical controls; or create a deceptive, infringing or unauthorized competing copy.`,`Reverse-engineering restrictions apply only to the extent permitted by law and do not override mandatory legal rights.`]],
        ['6. User content',[`You are responsible for questions, reflections and notes you enter. Your own original notes and reflections remain yours. Local Journal storage does not require you to grant Benedict Interactive a broad publication license in your personal content.`]],
        ['7. Local storage and data loss',[`Reading locks, preferences, profile details and Journal data rely on browser/device storage. Clearing site data, uninstalling, changing devices, privacy tools, storage pressure, browser changes or device failure may erase local information.`,`Unless a feature expressly states otherwise, there is no cloud backup or account recovery. Save anything important outside the app.`]],
        ['8. Save, Share and external destinations',[`Save/Share may hand exported content to the browser, operating system or external destination you choose. Once you select another app/service, that provider’s terms and privacy practices apply. Benedict Interactive does not control what an external recipient does with content you voluntarily send.`]],
        ['9. Voluntary support and PromptPay',[`Support is voluntary and does not buy better readings, alter card selection, improve luck, change probability, create spiritual status or unlock feature priority. PromptPay shows a QR destination and recipient information only; payment processing occurs through your bank/payment infrastructure outside the app.`,`Verify recipient name and amount in your banking app before confirming. The app does not receive bank credentials or independently confirm payment success.`]],
        ['10. Third-party services and marks',[`External fonts, payment systems, platforms and services remain subject to their own terms, licenses and policies. Descriptive use of a name/mark does not imply sponsorship, endorsement or affiliation unless expressly stated.`]],
        ['11. Intellectual property',[`Use of the app does not transfer intellectual-property ownership. The Copyright & Intellectual Property Notice and Proprietary License form part of the legal framework for protected materials.`]],
        ['12. Availability and changes',[`The app may be updated, corrected, redesigned, suspended or discontinued. Browser/OS/storage/network/third-party dependencies may behave differently across devices. Uninterrupted or error-free availability is not promised.`]],
        ['13. No outcome warranty',[`To the fullest extent permitted by law, the app is provided “as is” and “as available,” without guarantees of a particular spiritual, personal, financial, health, relationship or future outcome. Mandatory consumer warranties remain unaffected.`]],
        ['14. Limitation of liability',[`To the fullest extent permitted by law, Benedict Interactive and the applicable rights holder are not liable for indirect, incidental, special, consequential or purely speculative loss arising from treating reflective readings as certainty, loss of local data, third-party behavior or unsupported use.`,`Nothing excludes liability or consumer protections that applicable law does not allow to be excluded or limited.`]],
        ['15. Changes, governing law and language',[`The legal version and last-updated date are shown in the app. Material changes may be presented before or when they take effect; affirmative consent will be requested if applicable law requires it.`,`To the extent permitted by law, these Terms are governed by the laws of Thailand without depriving consumers of mandatory protections in their country or habitual residence. If translations conflict, the English reference text controls only to the extent permitted by law.`]],
        ['16. Severability and no waiver',[`If a provision is unenforceable, remaining provisions continue to the extent legally possible. Failure to enforce a provision does not by itself waive it.`]],
        ['17. Legal capacity and guardian involvement',[`If applicable law does not allow you to enter these Terms on your own, use the app only with the involvement and permission of a parent or legal guardian to the extent required by law. Optional profile age information is not an identity or legal-age verification service.`]],
        ['18. Entire framework and contact',[`These Terms operate together with the Copyright & Intellectual Property Notice, Privacy Policy, Third-Party Notices and any specific in-app notice that applies to a feature. They do not override mandatory law. Legal or licensing questions may be sent through an official Benedict Interactive contact channel when one is published.`]]
      ]},
      th:{title:'ข้อกำหนดการใช้งาน',subtitle:'กติกาสำหรับการเข้าถึงและใช้งาน Little Ganesha Tarot',sections:[
        ['1. การยอมรับข้อกำหนด',[`เมื่อเข้าถึงหรือใช้งาน Little Ganesha Tarot — The Golden Path คุณตกลงปฏิบัติตามข้อกำหนดนี้ในขอบเขตที่กฎหมายรับรองให้เกิดข้อตกลงได้ หากไม่ยอมรับ โปรดหยุดใช้งาน ทั้งนี้สิทธิ์ผู้บริโภคและสิทธิ์อื่นที่กฎหมายห้ามตัดออกยังคงมีผล`,`ข้อกำหนดนี้ครอบคลุมตัวแอป ฟีเจอร์ในเครื่อง ผลการอ่าน หน้าสนับสนุน และงานที่ได้รับการคุ้มครอง บริการภายนอกอาจมีข้อกำหนดของผู้ให้บริการนั้นเพิ่มเติม`]],
        ['2. ลักษณะของบริการ',[`Little Ganesha Tarot เป็นประสบการณ์ Tarot เพื่อการทบทวนและสำรวจตนเอง ผลการเปิดไพ่ เลขมงคล และเนื้อหาที่เกี่ยวข้องไม่ใช่การรับประกันอนาคต และไม่ควรใช้เป็นข้อเท็จจริงแน่นอนเกี่ยวกับเหตุการณ์ในอนาคตหรือความคิดส่วนตัวของบุคคลอื่น`,`แอปไม่ได้ให้การวินิจฉัยหรือรักษาทางการแพทย์ คำแนะนำทางกฎหมาย คำแนะนำทางการเงิน/การลงทุน คำแนะนำการพนัน บริการฉุกเฉิน หรือบริการวิชาชีพที่ถูกกำกับดูแล`]],
        ['3. สิทธิ์ใช้งานส่วนบุคคลแบบจำกัด',[`คุณได้รับสิทธิ์แบบจำกัด เพิกถอนได้ ไม่ผูกขาด และโอนไม่ได้ เพื่อเข้าถึงและใช้งานแอปตามวัตถุประสงค์ส่วนบุคคลทั่วไป สิทธิ์นี้เป็นสิทธิ์ใช้งาน ไม่ใช่การโอนกรรมสิทธิ์ในซอฟต์แวร์ งานภาพ งานเขียน หรือทรัพย์สินที่ได้รับการคุ้มครอง`]],
        ['4. การแคปหน้าจอและการแชร์ส่วนตัว',[`คุณสามารถแคปหน้าจอจากการใช้งานของตัวเอง และใช้ผลลัพธ์จาก Save/Share เพื่อการส่วนตัวที่ไม่ใช่เชิงพาณิชย์ได้ รวมถึงแชร์ผลการอ่านของตัวเองบนบัญชีโซเชียลส่วนตัวตามปกติ`,`สิทธิ์นี้ไม่ครอบคลุมการเผยแพร่สำรับทั้งชุดเป็นคลัง asset การแจกไฟล์ไพ่ต้นฉบับ การขายสินค้าที่อาศัยการคัดลอกข้อความ/งานภาพ การลบแบรนด์เพื่ออ้างผลงาน การใช้เนื้อหาในคอร์ส/สินค้าเก็บเงิน หรือการทำสำเนาแอปจำนวนมาก การที่แอปไม่บล็อกการแคปหน้าจอไม่ได้หมายถึงการอนุญาตการใช้งานเหล่านี้`]],
        ['5. พฤติกรรมที่ห้าม',[`ห้ามใช้แอปเพื่อฝ่าฝืนกฎหมายหรือสิทธิ์ผู้อื่น รบกวนการทำงาน/ความปลอดภัย แอบอ้างเป็น Benedict Interactive เผยแพร่มัลแวร์ ใช้ช่องโหว่โดยไม่มีสิทธิ์ scrape หรือดึงเนื้อหาจำนวนมาก หลีกเลี่ยงมาตรการทางเทคนิค หรือสร้างสำเนาที่หลอกลวง ละเมิดสิทธิ์ หรือแข่งขันโดยไม่ได้รับอนุญาต`,`ข้อจำกัด reverse engineering มีผลเฉพาะเท่าที่กฎหมายอนุญาตและไม่ลบล้างสิทธิ์บังคับตามกฎหมาย`]],
        ['6. เนื้อหาที่ผู้ใช้สร้าง',[`คุณรับผิดชอบต่อคำถาม ข้อความสะท้อนใจ และบันทึกที่พิมพ์ลงในแอป ข้อความต้นฉบับที่คุณเขียนเองยังคงเป็นของคุณ การเก็บ Journal ในเครื่องไม่ได้ทำให้ Benedict Interactive ได้รับสิทธิ์เผยแพร่เนื้อหาส่วนตัวของคุณอย่างกว้างขวาง`]],
        ['7. การเก็บข้อมูลในเครื่องและความเสี่ยงที่ข้อมูลสูญหาย',[`การล็อกผลประจำวัน การตั้งค่า โปรไฟล์ และ Journal พึ่งพา local storage/IndexedDB การล้างข้อมูลเว็บไซต์ ถอนการติดตั้ง เปลี่ยนอุปกรณ์ เครื่องมือความเป็นส่วนตัว พื้นที่จัดเก็บไม่พอ การเปลี่ยนเบราว์เซอร์ หรืออุปกรณ์เสีย อาจทำให้ข้อมูลหาย`,`เว้นแต่ฟีเจอร์ระบุไว้ต่างหาก ปัจจุบันไม่มี cloud backup หรือระบบบัญชีเพื่อกู้ข้อมูล ควรบันทึกสิ่งสำคัญไว้นอกแอปด้วยตัวเอง`]],
        ['8. Save, Share และปลายทางภายนอก',[`Save/Share อาจส่งผลลัพธ์ไปยังเบราว์เซอร์ ระบบปฏิบัติการ หรือปลายทางภายนอกที่คุณเลือก เมื่อเลือกบริการภายนอกแล้ว ข้อกำหนดและนโยบายของบริการนั้นจะมีผล Benedict Interactive ไม่ควบคุมการใช้งานของผู้รับภายนอก`]],
        ['9. การสนับสนุนโดยสมัครใจและ PromptPay',[`การสนับสนุนเป็นทางเลือก ไม่ได้ซื้อคำอ่านที่ดีกว่า ไม่เปลี่ยนการเลือกไพ่ ไม่เพิ่มโชค ไม่เปลี่ยนความน่าจะเป็น ไม่เพิ่มสถานะทางจิตวิญญาณ และไม่ให้สิทธิ์เข้าถึงก่อนผู้อื่น พร้อมเพย์แสดง QR และข้อมูลผู้รับเท่านั้น ธุรกรรมเกิดผ่านธนาคาร/ระบบชำระเงินภายนอก`,`ตรวจสอบชื่อผู้รับและจำนวนเงินในแอปธนาคารก่อนยืนยัน แอปไม่ได้รับรหัสธนาคารและไม่ยืนยันธุรกรรมได้ด้วยตนเอง`]],
        ['10. บริการและเครื่องหมายของบุคคลที่สาม',[`ฟอนต์ ระบบชำระเงิน แพลตฟอร์ม และบริการภายนอกอยู่ภายใต้ข้อกำหนด ใบอนุญาต และนโยบายของเจ้าของ การเอ่ยชื่อเพื่ออธิบายการทำงานไม่หมายถึงการสนับสนุน รับรอง หรือเป็นพันธมิตร เว้นแต่ระบุชัดเจน`]],
        ['11. ทรัพย์สินทางปัญญา',[`การใช้แอปไม่ได้โอนกรรมสิทธิ์ทางทรัพย์สินทางปัญญา ประกาศลิขสิทธิ์และ Proprietary License เป็นส่วนหนึ่งของกรอบสิทธิ์สำหรับเนื้อหาและซอฟต์แวร์ของแอป`]],
        ['12. ความพร้อมใช้งานและการเปลี่ยนแปลง',[`แอปอาจอัปเดต แก้ไข ออกแบบใหม่ ระงับ หรือยุติได้ ฟีเจอร์ที่พึ่งพาเบราว์เซอร์ ระบบปฏิบัติการ พื้นที่จัดเก็บ เครือข่าย หรือบริการภายนอกอาจทำงานไม่เหมือนกันทุกอุปกรณ์ และไม่รับประกันว่าจะไม่มีข้อผิดพลาดตลอดเวลา`]],
        ['13. ไม่มีการรับประกันผลลัพธ์',[`เท่าที่กฎหมายอนุญาต แอปให้บริการตามสภาพและตามความพร้อมใช้งาน โดยไม่รับประกันผลลัพธ์เฉพาะด้านจิตวิญญาณ ชีวิตส่วนตัว การเงิน สุขภาพ ความสัมพันธ์ หรืออนาคต สิทธิ์ผู้บริโภคบังคับยังคงมีผล`]],
        ['14. การจำกัดความรับผิด',[`เท่าที่กฎหมายอนุญาต Benedict Interactive และผู้ถือสิทธิ์ที่เกี่ยวข้องไม่รับผิดสำหรับความเสียหายทางอ้อม พิเศษ ต่อเนื่อง หรือเชิงคาดคะเนจากการยึดผลการอ่านเป็นข้อเท็จจริง การสูญเสียข้อมูลในเครื่อง พฤติกรรมของบริการภายนอก หรือการใช้งานนอกขอบเขต`,`ไม่มีข้อความใดตัดความรับผิดหรือสิทธิ์ผู้บริโภคที่กฎหมายห้ามตัดออก`]],
        ['15. การเปลี่ยนแปลง กฎหมายที่ใช้บังคับ และภาษา',[`แอปแสดงเวอร์ชันเอกสารและวันที่ปรับปรุง การเปลี่ยนสำคัญอาจแจ้งก่อนหรือเมื่อมีผล และจะขอความยินยอมชัดแจ้งถ้ากฎหมายกำหนด`,`เท่าที่กฎหมายอนุญาต ข้อกำหนดนี้อยู่ภายใต้กฎหมายไทย โดยไม่ตัดสิทธิ์ผู้บริโภคบังคับในประเทศ/ถิ่นที่พำนักของผู้ใช้ หากฉบับแปลขัดกัน ให้ใช้ภาษาอังกฤษเป็นฉบับอ้างอิงเฉพาะเท่าที่กฎหมายอนุญาต`]],
        ['16. การแยกข้อกำหนดและการไม่สละสิทธิ์',[`หากข้อใดใช้บังคับไม่ได้ ให้ข้ออื่นยังคงมีผลเท่าที่กฎหมายทำได้ การไม่บังคับใช้ข้อใดในบางครั้งไม่ถือเป็นการสละสิทธิ์โดยอัตโนมัติ`]],
        ['17. ความสามารถตามกฎหมายและผู้ปกครอง',[`หากกฎหมายในพื้นที่ของคุณยังไม่อนุญาตให้คุณยอมรับข้อกำหนดนี้ได้ด้วยตนเอง โปรดใช้แอปโดยมีพ่อแม่หรือผู้ปกครองตามกฎหมายมีส่วนร่วมและอนุญาตเท่าที่กฎหมายกำหนด ข้อมูลอายุในโปรไฟล์แบบไม่บังคับไม่ใช่ระบบยืนยันตัวตนหรือยืนยันอายุทางกฎหมาย`]],
        ['18. กรอบเอกสารทั้งหมดและการติดต่อ',[`ข้อกำหนดนี้ใช้ร่วมกับประกาศลิขสิทธิ์และทรัพย์สินทางปัญญา นโยบายความเป็นส่วนตัว ประกาศบุคคลที่สาม และข้อความเฉพาะที่ใช้กับแต่ละฟีเจอร์ โดยไม่ลบล้างกฎหมายบังคับ คำถามด้านกฎหมายหรือ licensing สามารถส่งผ่านช่องทางติดต่อทางการของ Benedict Interactive เมื่อมีการประกาศใช้งาน`]]
      ]},
      hi:{title:'उपयोग की शर्तें',subtitle:'Little Ganesha Tarot को एक्सेस और उपयोग करने के नियम।',sections:[
        ['1. इन शर्तों से सहमति',[`Legal notice दिखने पर “सहमत हूँ और आगे बढ़ें” चुनकर, या उस acceptance के बाद Little Ganesha Tarot — The Golden Path का उपयोग जारी रखकर, आप इन शर्तों से सहमत होते हैं, जितनी सीमा तक लागू कानून के तहत binding agreement बन सकता है। सहमत न हों तो उपयोग जारी न रखें। Mandatory consumer rights और non-waivable protections बने रहते हैं।`,`ये शर्तें app, local features, reading outputs, support screens और protected materials पर लागू हैं। External services की अलग terms लागू हो सकती हैं।`]],
        ['2. सेवा का स्वरूप',[`Little Ganesha Tarot एक reflective tarot और self-exploration experience है। Tarot readings, Lucky Numbers और related material guaranteed prediction नहीं हैं और future events या किसी दूसरे व्यक्ति के private thoughts की factual certainty नहीं माने जाने चाहिए।`,`App medical diagnosis/treatment, legal advice, financial/investment advice, gambling advice, emergency service या अन्य regulated professional service नहीं देता।`]],
        ['3. सीमित व्यक्तिगत उपयोग लाइसेंस',[`आपको ordinary personal use के लिए limited, revocable, non-exclusive, non-transferable permission मिलती है। यह service use करने का अधिकार है; software, artwork, writing या protected material का ownership transfer नहीं।`]],
        ['4. Screenshots और personal sharing',[`आप अपने app use के screenshots ले सकते हैं और Save/Share outputs का personal, non-commercial उपयोग कर सकते हैं। अपनी reading personal social account पर सामान्य रूप से share करना अनुमत है।`,`यह full deck asset archive, clean card files redistribution, copied app text/art पर आधारित paid products, authorship गलत दिखाने के लिए branding removal, paid course/product use या mass copying की अनुमति नहीं देता। Screenshot blocking न होना इन उपयोगों की consent नहीं है।`]],
        ['5. निषिद्ध आचरण',[`Law/third-party rights violation, operation/security interference, Benedict Interactive impersonation, malware, unauthorized vulnerability exploitation, protected content scraping/bulk extraction, technical controls bypass या deceptive/infringing/unauthorized competing copy निषिद्ध हैं।`,`Reverse-engineering restrictions केवल कानून की अनुमति तक लागू हैं और mandatory rights को override नहीं करतीं।`]],
        ['6. User content',[`आप अपने questions, reflections और notes के लिए जिम्मेदार हैं। आपके original notes/reflections आपके ही रहते हैं। Local Journal storage Benedict Interactive को broad publication license नहीं देता।`]],
        ['7. Local storage और data loss',[`Reading locks, preferences, profile details और Journal browser/device storage पर निर्भर हैं। Site data clear, uninstall, device change, privacy tools, storage pressure, browser change या device failure local information मिटा सकते हैं।`,`जब तक feature अलग से न कहे, cloud backup/account recovery नहीं है। Important content app के बाहर save करें।`]],
        ['8. Save, Share और external destinations',[`Save/Share exported content को browser/OS/आपके चुने external destination तक दे सकता है। External service चुनने के बाद उसकी terms/privacy practices लागू होती हैं।`]],
        ['9. Voluntary support और PromptPay',[`Support voluntary है और better readings, अलग card selection, luck/probability/spiritual status या feature priority नहीं खरीदता। PromptPay केवल QR destination और recipient information दिखाता है; payment bank/payment infrastructure में app से बाहर process होता है।`,`Confirmation से पहले banking app में recipient name और amount जाँचें। App bank credentials नहीं लेता और payment success independently verify नहीं करता।`]],
        ['10. Third-party services और marks',[`External fonts, payment systems, platforms और services अपनी terms/licenses/policies के अधीन रहते हैं। Descriptive mention sponsorship/endorsement/affiliation नहीं दर्शाता, जब तक स्पष्ट रूप से न कहा जाए।`]],
        ['11. Intellectual property',[`App use intellectual-property ownership transfer नहीं करता। Copyright/IP Notice और Proprietary License protected materials के legal framework का हिस्सा हैं।`]],
        ['12. Availability और changes',[`App update, correct, redesign, suspend या discontinue हो सकता है। Browser/OS/storage/network/third-party dependencies devices पर अलग behave कर सकती हैं। Uninterrupted/error-free availability की guarantee नहीं।`]],
        ['13. No outcome warranty',[`Applicable law की सीमा तक app “as is”/“as available” है और spiritual, personal, financial, health, relationship या future outcome की guarantee नहीं देता। Mandatory consumer warranties unaffected हैं।`]],
        ['14. Liability limitation',[`Applicable law की सीमा तक Benedict Interactive और rights holder reflective readings को certainty की तरह मानने, local data loss, third-party behavior या unsupported use से होने वाले indirect/special/consequential/speculative loss के लिए liable नहीं होंगे। Mandatory liability/consumer protections unaffected हैं।`]],
        ['15. Changes, governing law और language',[`Legal version/updated date app में दिखती है। Material changes प्रभावी होने से पहले/साथ दिख सकते हैं; law की जरूरत पर affirmative consent माँगी जाएगी।`,`Law की अनुमति तक Thailand law लागू होगा, लेकिन user के country/habitual residence की mandatory consumer protections नहीं हटतीं। Translation conflict में English reference text केवल law की अनुमति तक control करेगा।`]],
        ['16. Severability और no waiver',[`कोई provision unenforceable हो तो बाकी provisions legal सीमा तक जारी रहेंगे। Enforcement delay अपने-आप waiver नहीं है।`]],
        ['17. Legal capacity और guardian involvement',[`अगर applicable law आपको इन Terms को स्वयं स्वीकार करने की कानूनी क्षमता नहीं देता, तो जहाँ कानून माँगे वहाँ parent/legal guardian की भागीदारी और अनुमति के साथ app use करें। Optional profile age information identity/legal-age verification service नहीं है।`]],
        ['18. पूरा legal framework और contact',[`ये Terms Copyright & Intellectual Property Notice, Privacy Policy, Third-Party Notices और feature-specific in-app notices के साथ मिलकर लागू होते हैं। ये mandatory law को override नहीं करते। Legal/licensing questions official Benedict Interactive contact channel उपलब्ध होने पर भेजे जा सकते हैं।`]]
      ]}
    },

    privacy: {
      en:{title:'Privacy Policy',subtitle:'What stays on your device, what can leave it, and the controls you have.',sections:[
        ['1. Privacy approach',[`Little Ganesha Tarot is designed as a local-first application. In the current release there is no user account, cloud Journal, advertising SDK, behavioural advertising system or product analytics SDK operated by Benedict Interactive.`,`This Policy describes the application as it exists in this release. If a future feature materially changes how personal data is handled, the Policy will be updated before or when that feature is introduced, and consent will be requested where applicable law requires it.`]],
        ['2. Information you choose to store locally',[`Optional profile information such as your display name and date of birth is stored in browser/device storage. Reading preferences, language, motion/audio settings, daily reading state, and the accepted legal-version/timestamp used to remember your acknowledgement are also stored locally so the app can behave consistently on your device.`,`These local records are used by the app on your device. Benedict Interactive does not intentionally receive them through an application backend in the current release.`]],
        ['3. Ask Ganesha privacy',[`Ask Ganesha uses your question on the device to create the reading context and to preserve same-day semantic consistency. Its reading store keeps a fingerprint and structured semantic descriptors together with reading state; it does not store the full exact question text in that reading store.`,`Your exact Ask Ganesha wording can be saved in the Journal only if you turn on “Save exact Ask Ganesha questions.” That option is OFF by default.`]],
        ['4. Journal and reflections',[`The Journal is stored locally in IndexedDB on your device. It may contain saved reading snapshots, card identifiers, Lucky Numbers, focus information, your reflections, bookmarks and—only when you enable the relevant option—the exact wording of Ask Ganesha questions.`,`Journal auto-save can be controlled in Settings. You can delete one entry, delete multiple selected entries, or clear Journal data. Deleting a Journal copy does not reset the original same-day tarot or Lucky Numbers state.`]],
        ['5. Local storage is not cloud backup',[`Local browser/device storage can be lost if you clear site data, uninstall or reset the app, change browser or device, use storage-cleaning/privacy tools, run out of storage, or experience device failure. The current release does not provide an account-based recovery service or cloud backup for the Journal.`,`Local app data is not separately encrypted by Little Ganesha Tarot beyond protections provided by your browser, operating system and device. Use an appropriate device lock and avoid storing information you would not want another person with access to your unlocked device to see.`]],
        ['6. Save, Share and screenshots',[`Save and Share are user-initiated actions. Saving can create an image on your device. Sharing can pass an exported image or text to your operating system, browser, share sheet or a third-party destination you select. Once you choose an external destination, that provider’s privacy practices apply.`,`The app does not technically block ordinary screenshots. A screenshot is created and handled by your operating system/device. Personal, non-commercial screenshots are permitted under the Terms, but this does not grant broader rights to redistribute protected assets.`]],
        ['7. Voluntary support and PromptPay',[`The PromptPay support screen displays a QR code and recipient-identification information so you can initiate a voluntary payment in your own banking application. Little Ganesha Tarot does not ask for or receive your banking password, PIN, one-time password, card data or bank login credentials.`,`The payment is processed outside the app by your bank/payment infrastructure. The current app does not independently receive or verify payment confirmation. Always verify the recipient name and amount in your banking app before authorising a transfer.`]],
        ['8. Hosting, fonts and ordinary connection data',[`Although personal reading/profile/Journal data is local-first, using the web/PWA can still create ordinary network requests. The hosting provider and network intermediaries may receive standard technical request data such as IP address, timestamps, requested files and browser/device information as part of delivering the app.`,`The current interface also requests fonts from Google Fonts infrastructure. Google or its service providers may receive ordinary connection/request metadata under their own privacy terms. Benedict Interactive does not use those requests to build a behavioural profile of you.`]],
        ['9. Analytics, advertising and sale of personal data',[`The current release contains no Benedict Interactive behavioural-advertising SDK and no product analytics SDK. Benedict Interactive does not sell personal profile, Journal or reading data to advertisers in this release.`,`If analytics, cloud sync, accounts, crash reporting or another remote-data feature is introduced later, this Policy must be updated to describe the data flow before or when the feature becomes active.`]],
        ['10. Retention and deletion',[`Functional reading records generally persist only for the period required by the applicable daily-reading rule or until browser storage is removed, while profile/preferences and Journal entries can remain locally until you change or delete them. Exact retention can also depend on browser and operating-system storage policies.`,`Use the controls in Settings and Journal to clear data that the app exposes for deletion. Clearing browser/site storage at the operating-system or browser level can remove additional local app data.`]],
        ['11. Security and sensible use',[`The app is designed to minimise remote collection, but no device, browser, storage system or network can be promised to be absolutely secure. Keep your device and browser updated, protect access to your device, and avoid entering passwords, financial credentials, government identifiers, medical records or other highly sensitive secrets into tarot questions or reflections.`]],
        ['12. Children and legal capacity',[`Little Ganesha Tarot is not designed to solicit children’s personal data. If you are not legally able to consent to data handling or enter into the applicable Terms in your jurisdiction, use the app only with the involvement of a parent or legal guardian where required by law.`,`Because the current product is local-first and has no account-age verification service, a date of birth entered in the optional profile is not used as a legal age-verification mechanism.`]],
        ['13. International use and mandatory rights',[`The app can be used from multiple countries. Privacy, consumer and data-protection rights can vary by jurisdiction. Nothing in this Policy is intended to remove a right that applicable law makes non-waivable.`]],
        ['14. Changes and contact',[`This Policy displays its legal version and update date. Material changes to remote collection, sharing or processing will be reflected in an updated policy, with additional notice or consent where required by law.`,`Privacy, licensing or legal questions may be submitted through the official Benedict Interactive contact channel when available. No unofficial social account should be treated as a legal contact unless Benedict Interactive identifies it as such.`]]
      ]},
      th:{title:'นโยบายความเป็นส่วนตัว',subtitle:'ข้อมูลอะไรอยู่ในเครื่อง อะไรอาจออกจากเครื่อง และคุณควบคุมอะไรได้บ้าง',sections:[
        ['1. แนวทางด้านความเป็นส่วนตัว',[`Little Ganesha Tarot ออกแบบแบบ local-first เป็นหลัก ในรุ่นปัจจุบันไม่มีบัญชีผู้ใช้ ไม่มี Journal บนคลาวด์ ไม่มี SDK โฆษณาหรือโฆษณาตามพฤติกรรม และไม่มี SDK วิเคราะห์การใช้งานผลิตภัณฑ์ที่ Benedict Interactive เป็นผู้ดำเนินการ`,`นโยบายนี้อธิบายแอปตามสภาพของรุ่นปัจจุบัน หากฟีเจอร์ในอนาคตเปลี่ยนวิธีจัดการข้อมูลส่วนบุคคลอย่างมีนัยสำคัญ นโยบายจะถูกปรับก่อนหรือพร้อมกับการเปิดใช้ฟีเจอร์นั้น และจะขอความยินยอมเมื่อกฎหมายกำหนด`]],
        ['2. ข้อมูลที่คุณเลือกเก็บไว้บนอุปกรณ์',[`ข้อมูลโปรไฟล์ที่ไม่บังคับ เช่น ชื่อที่ใช้แสดงและวันเดือนปีเกิด จะถูกเก็บในพื้นที่จัดเก็บของเบราว์เซอร์/อุปกรณ์ การตั้งค่าภาษา การเคลื่อนไหว เสียง สถานะผลการอ่านประจำวัน รวมถึงเวอร์ชันข้อกำหนดและเวลาที่อุปกรณ์บันทึกว่าคุณยอมรับ จะถูกเก็บไว้ในเครื่องเพื่อให้แอปทำงานต่อเนื่อง`,`ในรุ่นปัจจุบัน ข้อมูลเหล่านี้ถูกใช้โดยแอปบนอุปกรณ์ของคุณ และ Benedict Interactive ไม่ได้ตั้งใจรับข้อมูลดังกล่าวผ่าน backend ของแอป`]],
        ['3. ความเป็นส่วนตัวของ “ถามพระพิฆเนศน้อย”',[`Ask Ganesha ใช้ข้อความคำถามบนอุปกรณ์เพื่อกำหนดบริบทการอ่านและรักษาความสอดคล้องของคำถามที่มีความหมายเดียวกันภายในวันเดียวกัน พื้นที่เก็บผลของโหมดนี้เก็บ fingerprint และตัวบ่งชี้เชิงความหมายแบบมีโครงสร้างร่วมกับสถานะผลการอ่าน แต่ไม่ได้เก็บข้อความคำถามเต็มแบบตรงๆ ใน reading store นั้น`,`ข้อความคำถามจริงจะถูกเก็บใน Journal ก็ต่อเมื่อคุณเปิดตัวเลือก “เก็บข้อความคำถามจริงจากถามพระพิฆเนศน้อย” ซึ่งปิดไว้เป็นค่าเริ่มต้น`]],
        ['4. Journal และข้อความสะท้อนใจ',[`Journal ถูกเก็บแบบ local ใน IndexedDB บนอุปกรณ์ของคุณ และอาจประกอบด้วย snapshot ของคำอ่าน รหัสไพ่ Lucky Numbers หัวข้อ Focus ข้อความสะท้อนใจ ที่คั่นรายการ และ—เฉพาะเมื่อคุณเปิดตัวเลือกที่เกี่ยวข้อง—ข้อความคำถามจริงของ Ask Ganesha`,`คุณควบคุมการเก็บอัตโนมัติได้ใน Settings และสามารถลบทีละรายการ เลือกหลายรายการแล้วลบ หรือเคลียร์ข้อมูล Journal ได้ การลบสำเนาใน Journal ไม่ได้รีเซ็ตผล Tarot หรือ Lucky Numbers ของวันนั้น`]],
        ['5. ข้อมูลในเครื่องไม่ใช่ cloud backup',[`ข้อมูล local อาจหายเมื่อคุณล้างข้อมูลเว็บไซต์ ถอนการติดตั้งหรือรีเซ็ตแอป เปลี่ยนเบราว์เซอร์/อุปกรณ์ ใช้เครื่องมือเคลียร์พื้นที่หรือความเป็นส่วนตัว พื้นที่จัดเก็บเต็ม หรืออุปกรณ์เสีย รุ่นปัจจุบันไม่มีระบบบัญชีเพื่อกู้ Journal และไม่มี cloud backup`,`Little Ganesha Tarot ไม่ได้เข้ารหัสข้อมูล local เพิ่มอีกชั้นแยกจากระบบป้องกันของเบราว์เซอร์ ระบบปฏิบัติการ และอุปกรณ์ ควรตั้งค่าล็อกอุปกรณ์ที่เหมาะสม และหลีกเลี่ยงการเก็บข้อมูลที่คุณไม่ต้องการให้ผู้ที่เข้าถึงเครื่องซึ่งปลดล็อกแล้วเห็น`]],
        ['6. Save, Share และการแคปหน้าจอ',[`Save และ Share ทำงานเมื่อผู้ใช้เป็นผู้สั่งเอง การบันทึกอาจสร้างไฟล์ภาพบนอุปกรณ์ ส่วนการแชร์อาจส่งภาพหรือข้อความที่ export ไปยังระบบปฏิบัติการ เบราว์เซอร์ share sheet หรือบริการภายนอกที่คุณเลือก หลังจากเลือกปลายทางภายนอกแล้ว นโยบายความเป็นส่วนตัวของบริการนั้นจะมีผล`,`แอปไม่ได้บล็อกการแคปหน้าจอทั่วไปในเชิงเทคนิค ภาพแคปถูกสร้างและจัดการโดยระบบปฏิบัติการ/อุปกรณ์ การแคปเพื่อใช้ส่วนตัวที่ไม่ใช่เชิงพาณิชย์ได้รับอนุญาตตาม Terms แต่ไม่ได้ให้สิทธิ์เพิ่มเติมในการแจกจ่ายสินทรัพย์ที่ได้รับการคุ้มครอง`]],
        ['7. การสนับสนุนโดยสมัครใจและ PromptPay',[`หน้าสนับสนุน PromptPay แสดง QR และข้อมูลระบุผู้รับเพื่อให้คุณเริ่มทำรายการผ่านแอปธนาคารของตัวเอง Little Ganesha Tarot ไม่ขอและไม่รับรหัสผ่านธนาคาร PIN OTP ข้อมูลบัตร หรือข้อมูลล็อกอินธนาคารของคุณ`,`ธุรกรรมถูกประมวลผลภายนอกแอปโดยธนาคาร/โครงสร้างพื้นฐานการชำระเงิน และแอปรุ่นปัจจุบันไม่ได้รับหรือยืนยันสถานะการชำระเงินได้ด้วยตัวเอง กรุณาตรวจชื่อผู้รับและจำนวนเงินในแอปธนาคารก่อนอนุมัติ`]],
        ['8. Hosting, ฟอนต์ และข้อมูลการเชื่อมต่อทั่วไป',[`แม้ข้อมูลโปรไฟล์ คำอ่าน และ Journal จะออกแบบแบบ local-first แต่การใช้งาน web/PWA ยังอาจสร้างคำขอผ่านเครือข่าย ผู้ให้บริการ hosting และตัวกลางเครือข่ายอาจได้รับข้อมูลทางเทคนิคมาตรฐาน เช่น IP address เวลา ไฟล์ที่ร้องขอ และข้อมูลเบราว์เซอร์/อุปกรณ์ เพื่อส่งแอปมายังเครื่องของคุณ`,`หน้าตาแอปรุ่นปัจจุบันยังเรียกฟอนต์จากโครงสร้างพื้นฐานของ Google Fonts ซึ่ง Google หรือผู้ให้บริการของ Google อาจได้รับข้อมูลการเชื่อมต่อ/คำขอมาตรฐานตามนโยบายของตน Benedict Interactive ไม่ได้นำคำขอเหล่านี้ไปสร้างโปรไฟล์พฤติกรรมของผู้ใช้`]],
        ['9. Analytics โฆษณา และการขายข้อมูล',[`รุ่นปัจจุบันไม่มี SDK โฆษณาตามพฤติกรรมของ Benedict Interactive และไม่มี SDK วิเคราะห์ผลิตภัณฑ์ Benedict Interactive ไม่ขายข้อมูลโปรไฟล์ Journal หรือข้อมูลผลการอ่านให้ผู้ลงโฆษณาในรุ่นนี้`,`หากอนาคตเพิ่ม analytics, cloud sync, account, crash reporting หรือฟีเจอร์ที่ส่งข้อมูลระยะไกล นโยบายนี้ต้องได้รับการปรับให้บอก data flow ก่อนหรือพร้อมกับการเปิดใช้ฟีเจอร์นั้น`]],
        ['10. ระยะเวลาการเก็บและการลบ',[`สถานะการอ่านบางประเภทจะอยู่ตามระยะที่จำเป็นต่อกติกาของวันนั้นหรือจนกว่าพื้นที่เก็บของเบราว์เซอร์ถูกล้าง ส่วนโปรไฟล์ การตั้งค่า และ Journal อาจอยู่ในเครื่องจนกว่าคุณจะเปลี่ยนหรือลบ ทั้งนี้นโยบายจัดการพื้นที่ของเบราว์เซอร์/ระบบปฏิบัติการอาจมีผลต่อระยะเวลาจริง`,`ใช้ตัวควบคุมใน Settings และ Journal เพื่อลบข้อมูลที่แอปเปิดให้จัดการ และสามารถล้าง site storage จากระดับเบราว์เซอร์/ระบบปฏิบัติการเพื่อลบข้อมูล local เพิ่มเติมได้`]],
        ['11. ความปลอดภัยและการใช้อย่างเหมาะสม',[`แอปออกแบบเพื่อลดการเก็บข้อมูลจากระยะไกล แต่ไม่มีอุปกรณ์ เบราว์เซอร์ ระบบจัดเก็บ หรือเครือข่ายใดรับประกันความปลอดภัยสมบูรณ์แบบได้ ควรอัปเดตอุปกรณ์และเบราว์เซอร์ ป้องกันการเข้าถึงเครื่อง และไม่พิมพ์รหัสผ่าน ข้อมูลธนาคาร เลขประจำตัวราชการ เวชระเบียน หรือความลับอ่อนไหวสูงลงในคำถาม Tarot หรือ Reflection`]],
        ['12. เด็กและความสามารถตามกฎหมาย',[`Little Ganesha Tarot ไม่ได้ออกแบบมาเพื่อร้องขอข้อมูลส่วนบุคคลของเด็ก หากกฎหมายในพื้นที่ของคุณกำหนดว่าคุณยังไม่สามารถให้ความยินยอมหรือทำข้อตกลงนี้เองได้ โปรดใช้แอปโดยมีพ่อแม่หรือผู้ปกครองตามกฎหมายมีส่วนร่วมตามที่กฎหมายกำหนด`,`เนื่องจากผลิตภัณฑ์ปัจจุบันเป็น local-first และไม่มีระบบยืนยันอายุผ่านบัญชี วันเดือนปีเกิดที่กรอกในโปรไฟล์แบบไม่บังคับจึงไม่ใช่ระบบตรวจอายุทางกฎหมาย`]],
        ['13. การใช้งานระหว่างประเทศและสิทธิ์ที่ตัดไม่ได้',[`แอปสามารถถูกใช้จากหลายประเทศ กฎหมายด้านความเป็นส่วนตัว ผู้บริโภค และข้อมูลส่วนบุคคลอาจแตกต่างกัน ไม่มีข้อความใดในนโยบายนี้ตั้งใจตัดสิทธิ์ที่กฎหมายกำหนดว่าไม่อาจสละหรือลดทอนได้`]],
        ['14. การเปลี่ยนแปลงและการติดต่อ',[`นโยบายจะแสดงเวอร์ชันเอกสารและวันที่ปรับปรุง การเปลี่ยนแปลงสำคัญที่เกี่ยวกับการเก็บ ส่ง หรือแชร์ข้อมูลระยะไกลจะถูกสะท้อนในนโยบายใหม่ พร้อมการแจ้งหรือการขอความยินยอมเพิ่มเติมเมื่อกฎหมายกำหนด`,`คำถามด้าน privacy, licensing หรือกฎหมายสามารถส่งผ่านช่องทางติดต่อทางการของ Benedict Interactive เมื่อมีการประกาศใช้งาน ไม่ควรถือบัญชีโซเชียลที่ไม่ถูกระบุอย่างเป็นทางการว่าเป็นช่องทางติดต่อทางกฎหมาย`]]
      ]},
      hi:{title:'गोपनीयता नीति',subtitle:'क्या आपके डिवाइस पर रहता है, क्या बाहर जा सकता है और आपके पास कौन-से नियंत्रण हैं।',sections:[
        ['1. Privacy approach',[`Little Ganesha Tarot local-first app के रूप में बनाया गया है। Current release में Benedict Interactive द्वारा चलाया गया user account, cloud Journal, advertising SDK, behavioural advertising system या product analytics SDK नहीं है।`,`यह Policy current release की वास्तविक data handling को बताती है। Future feature अगर personal-data flow materially बदलता है, तो feature के शुरू होने से पहले/साथ Policy update होगी और जहाँ कानून माँगे वहाँ consent लिया जाएगा।`]],
        ['2. आपके डिवाइस पर वैकल्पिक local information',[`Display name और date of birth जैसी optional profile information browser/device storage में रहती है। Language, motion/audio preferences, daily reading state और accepted legal version/timestamp भी app continuity तथा acknowledgement याद रखने के लिए locally store होते हैं।`,`Current release में ये local records आपके डिवाइस पर app द्वारा इस्तेमाल होते हैं; Benedict Interactive application backend के जरिए इन्हें जानबूझकर receive नहीं करता।`]],
        ['3. Ask Ganesha privacy',[`Ask Ganesha आपके प्रश्न को डिवाइस पर reading context बनाने और same-day semantic consistency रखने के लिए उपयोग करता है। Reading store fingerprint, structured semantic descriptors और reading state रखता है; उसमें पूरा exact question text store नहीं होता।`,`Exact Ask Ganesha wording Journal में केवल तभी save होता है जब आप “Save exact Ask Ganesha questions” विकल्प चालू करते हैं। यह default रूप से OFF है।`]],
        ['4. Journal और reflections',[`Journal आपके डिवाइस के IndexedDB में locally store होता है। इसमें saved reading snapshots, card identifiers, Lucky Numbers, focus, reflections, bookmarks और—केवल संबंधित विकल्प चालू होने पर—Ask Ganesha का exact question शामिल हो सकता है।`,`Settings में auto-save control उपलब्ध है। आप एक entry, कई selected entries या पूरा Journal data delete कर सकते हैं। Journal copy delete करने से original same-day tarot/Lucky Numbers state reset नहीं होता।`]],
        ['5. Local storage cloud backup नहीं है',[`Site data clear करने, app uninstall/reset, browser/device बदलने, privacy/cleanup tools, storage pressure या device failure से local information खो सकती है। Current release में Journal के लिए account-based recovery या cloud backup नहीं है।`,`Little Ganesha Tarot local app data को browser/OS/device protection से अलग अपनी encryption layer में encrypt नहीं करता। Device lock का उपयोग करें और ऐसी sensitive information न रखें जिसे unlocked device तक पहुँच रखने वाला व्यक्ति न देखे।`]],
        ['6. Save, Share और screenshots',[`Save और Share user-initiated actions हैं। Save आपके डिवाइस पर image बना सकता है। Share exported image/text को OS, browser, share sheet या आपके चुने third-party destination तक पहुँचा सकता है। External destination चुनने के बाद उसकी privacy practices लागू होती हैं।`,`App ordinary screenshots को technically block नहीं करता। Screenshot आपके operating system/device द्वारा बनाया और संभाला जाता है। Personal, non-commercial screenshots Terms के अंतर्गत अनुमत हैं, लेकिन इससे protected assets के व्यापक redistribution rights नहीं मिलते।`]],
        ['7. Voluntary support और PromptPay',[`PromptPay support screen QR और recipient identification information दिखाता है ताकि आप अपने banking app में voluntary transfer शुरू कर सकें। Little Ganesha Tarot bank password, PIN, OTP, card data या bank login credentials नहीं माँगता/लेता।`,`Payment app के बाहर bank/payment infrastructure द्वारा process होता है। Current app payment success independently receive या verify नहीं करता। Transfer authorise करने से पहले banking app में recipient name और amount जाँचें।`]],
        ['8. Hosting, fonts और ordinary connection data',[`Profile/reading/Journal data local-first होने के बावजूद web/PWA use ordinary network requests बनाता है। Hosting provider और network intermediaries delivery के लिए IP address, timestamp, requested files और browser/device information जैसी standard technical request data देख सकते हैं।`,`Current UI Google Fonts infrastructure से fonts request करता है। Google या उसके service providers अपनी privacy terms के तहत ordinary connection/request metadata प्राप्त कर सकते हैं। Benedict Interactive इन requests से behavioural profile नहीं बनाता।`]],
        ['9. Analytics, advertising और data sale',[`Current release में Benedict Interactive behavioural-advertising SDK या product analytics SDK नहीं है। Benedict Interactive इस release में personal profile, Journal या reading data advertisers को नहीं बेचता।`,`Future analytics, cloud sync, account, crash reporting या remote-data feature शुरू होने पर उसका data flow बताने के लिए Policy update होना जरूरी है।`]],
        ['10. Retention और deletion',[`Functional reading records applicable daily rule की जरूरत तक या browser storage हटने तक रह सकते हैं। Profile/preferences और Journal entries आपके बदलने/delete करने तक local रह सकते हैं; वास्तविक retention browser/OS storage policies से भी प्रभावित हो सकती है।`,`Settings/Journal के deletion controls का उपयोग करें। Browser/OS स्तर पर site storage clear करने से अतिरिक्त local app data हट सकता है।`]],
        ['11. Security और sensible use',[`Remote collection कम करने के बावजूद कोई device, browser, storage या network absolutely secure होने की guarantee नहीं देता। Device/browser updated रखें, device access सुरक्षित करें और tarot questions/reflections में passwords, banking credentials, government identifiers, medical records या अत्यधिक संवेदनशील secrets न लिखें।`]],
        ['12. Children और legal capacity',[`Little Ganesha Tarot बच्चों का personal data solicit करने के लिए design नहीं किया गया। अगर आपके jurisdiction में आप स्वयं consent/contract की कानूनी क्षमता नहीं रखते, तो जहाँ कानून माँगे वहाँ parent/legal guardian की भागीदारी के साथ app use करें।`,`Optional profile date of birth legal age-verification system नहीं है, क्योंकि current product local-first है और account-based age verification नहीं करता।`]],
        ['13. International use और mandatory rights',[`App कई देशों से इस्तेमाल किया जा सकता है और privacy/consumer/data-protection rights jurisdiction के अनुसार बदल सकते हैं। यह Policy किसी non-waivable legal right को हटाने के लिए नहीं है।`]],
        ['14. Changes और contact',[`Policy legal version और update date दिखाती है। Remote collection/sharing/processing में material change होने पर updated policy, और जहाँ कानून माँगे वहाँ additional notice/consent, दिया जाएगा।`,`Privacy, licensing या legal questions official Benedict Interactive contact channel उपलब्ध होने पर वहीं भेजे जा सकते हैं। किसी unofficial social account को legal contact न मानें जब तक उसे officially identify न किया जाए।`]]
      ]}
    },

    thirdParty: {
      en:{title:'Third-Party Notices',subtitle:'External technologies, services, marks and public-domain foundations used or referenced by the app.',sections:[
        ['1. Purpose of this notice',[`Little Ganesha Tarot includes or references technologies, fonts, platforms, payment rails, traditional tarot material and other third-party elements. Those materials remain subject to the rights, licences, terms and policies of their respective owners.`,`Nothing in this notice transfers third-party rights to Benedict Interactive, and mentioning a third party does not imply sponsorship, endorsement, partnership or affiliation unless expressly stated.`]],
        ['2. Google Fonts and typefaces',[`The current interface requests typefaces through Google Fonts infrastructure, including Cormorant Garamond, Noto Sans Thai, Noto Serif Thai, Noto Sans Devanagari and Noto Serif Devanagari. Typeface/font files remain subject to their upstream licences and notices.`,`Where a font is distributed under the SIL Open Font License or another open-font licence, that licence—not the Little Ganesha proprietary licence—governs the font itself. Google Fonts and Google are marks/services of their respective owner.`]],
        ['3. PromptPay and Thai QR Payment',[`PromptPay, Thai QR Payment, participating banks/payment infrastructure and associated names, logos or marks belong to or are administered by their respective owners/operators. Little Ganesha Tarot uses a recipient QR as a voluntary support destination and is not a bank, payment processor or PromptPay operator.`,`A payment relationship is between the user and the relevant banking/payment services. Display of a payment mark or compatibility reference does not imply that those operators sponsor or endorse Little Ganesha Tarot.`]],
        ['4. Buy Me a Coffee',[`Buy Me a Coffee is referenced in the current product as a planned international support channel and is not active until an official Benedict Interactive destination is configured. Buy Me a Coffee and its marks/services belong to their respective owner and are governed by that provider’s terms when used.`]],
        ['5. Browsers, operating systems and device platforms',[`References to browser, operating-system, app-install, share-sheet, storage, screenshot or other platform capabilities describe interoperability only. Platform names and marks remain property of their respective owners. Availability and behaviour depend on the user’s platform.`]],
        ['6. Tarot history, terminology and public-domain foundations',[`Traditional tarot concepts, historical facts, conventional card names/structures and public-domain source material are not claimed as exclusive property of Benedict Interactive. Little Ganesha Tarot’s proprietary claims apply to its protectable original code, text, artwork, selection, arrangement, editing, presentation and other original expression.`]],
        ['7. Open-source and third-party code',[`If a release incorporates third-party or open-source software, the applicable upstream licence and required notice govern that component. The proprietary licence for Little Ganesha Tarot does not cancel rights granted by a valid third-party licence.`,`When required, additional licence texts or attribution files may be distributed with the source or release package. If an upstream notice conflicts with a general statement here, the upstream licence controls for that component.`]],
        ['8. No implied endorsement',[`Compatibility, factual reference or technical use does not create an endorsement relationship. Unless a partnership is explicitly announced through an official Benedict Interactive channel, users should not infer sponsorship, certification or approval by a named third party.`]]
      ]},
      th:{title:'ประกาศเกี่ยวกับบุคคลที่สาม',subtitle:'เทคโนโลยี บริการ เครื่องหมาย และรากฐานสาธารณะที่แอปใช้หรืออ้างถึง',sections:[
        ['1. วัตถุประสงค์ของประกาศนี้',[`Little Ganesha Tarot ใช้หรืออ้างถึงเทคโนโลยี ฟอนต์ แพลตฟอร์ม ระบบชำระเงิน เนื้อหา Tarot ดั้งเดิม และองค์ประกอบของบุคคลที่สามบางส่วน สิ่งเหล่านั้นยังอยู่ภายใต้สิทธิ์ ใบอนุญาต ข้อกำหนด และนโยบายของเจ้าของแต่ละราย`,`ไม่มีข้อความใดในประกาศนี้โอนสิทธิ์ของบุคคลที่สามให้ Benedict Interactive และการเอ่ยชื่อไม่ได้หมายถึงการสนับสนุน รับรอง เป็นพันธมิตร หรือมีความเกี่ยวข้อง เว้นแต่จะระบุไว้ชัดเจน`]],
        ['2. Google Fonts และแบบอักษร',[`หน้าตาแอปรุ่นปัจจุบันเรียกแบบอักษรผ่านโครงสร้างพื้นฐานของ Google Fonts ได้แก่ Cormorant Garamond, Noto Sans Thai, Noto Serif Thai, Noto Sans Devanagari และ Noto Serif Devanagari ไฟล์ฟอนต์และแบบอักษรยังคงอยู่ภายใต้ใบอนุญาตและประกาศของแหล่งต้นทาง`,`ในกรณีที่ฟอนต์เผยแพร่ภายใต้ SIL Open Font License หรือใบอนุญาต open-font อื่น ให้ใบอนุญาตนั้นเป็นตัวควบคุมสิทธิ์ของตัวฟอนต์ ไม่ใช่ Proprietary License ของ Little Ganesha ส่วน Google Fonts และ Google เป็นชื่อ/เครื่องหมายของเจ้าของที่เกี่ยวข้อง`]],
        ['3. PromptPay และ Thai QR Payment',[`PromptPay, Thai QR Payment ธนาคาร/โครงสร้างพื้นฐานชำระเงินที่เกี่ยวข้อง รวมถึงชื่อ โลโก้ และเครื่องหมายที่เกี่ยวข้อง เป็นของหรืออยู่ภายใต้การดูแลของเจ้าของ/ผู้ดำเนินการแต่ละราย Little Ganesha Tarot ใช้ QR ผู้รับเป็นช่องทางสนับสนุนโดยสมัครใจ และไม่ได้เป็นธนาคาร ผู้ประมวลผลการชำระเงิน หรือผู้ให้บริการ PromptPay`,`ความสัมพันธ์ด้านการชำระเงินเกิดระหว่างผู้ใช้กับบริการธนาคาร/ชำระเงินที่เกี่ยวข้อง การแสดงเครื่องหมายหรือข้อความว่าใช้งานร่วมกันได้ ไม่ได้หมายความว่าผู้ดำเนินการเหล่านั้นสนับสนุนหรือรับรอง Little Ganesha Tarot`]],
        ['4. Buy Me a Coffee',[`Buy Me a Coffee ถูกระบุไว้ในผลิตภัณฑ์ปัจจุบันในฐานะช่องทางสนับสนุนต่างประเทศที่วางแผนไว้ และยังไม่เปิดใช้งานจนกว่าจะตั้งค่าปลายทางทางการของ Benedict Interactive ชื่อ เครื่องหมาย และบริการของ Buy Me a Coffee อยู่ภายใต้สิทธิ์และข้อกำหนดของเจ้าของบริการเมื่อมีการใช้งาน`]],
        ['5. เบราว์เซอร์ ระบบปฏิบัติการ และแพลตฟอร์มอุปกรณ์',[`การอ้างถึง browser, operating system, การติดตั้งแอป, share sheet, storage, screenshot หรือความสามารถของแพลตฟอร์มอื่น เป็นการอธิบายความเข้ากันได้เท่านั้น ชื่อและเครื่องหมายของแพลตฟอร์มยังเป็นของเจ้าของแต่ละราย และความพร้อม/พฤติกรรมขึ้นกับอุปกรณ์ของผู้ใช้`]],
        ['6. ประวัติ Tarot คำศัพท์ และรากฐานสาธารณสมบัติ',[`แนวคิด Tarot แบบดั้งเดิม ข้อเท็จจริงทางประวัติศาสตร์ ชื่อ/โครงสร้างไพ่ตามธรรมเนียม และวัสดุสาธารณสมบัติไม่ได้ถูกอ้างเป็นทรัพย์สินแต่เพียงผู้เดียวของ Benedict Interactive การอ้างสิทธิ์ของ Little Ganesha Tarot ครอบคลุมเฉพาะโค้ด ข้อความ งานภาพ การคัดเลือก การจัดเรียง การแก้ไข การนำเสนอ และรูปแบบการแสดงออกต้นฉบับที่กฎหมายคุ้มครอง`]],
        ['7. ซอฟต์แวร์โอเพนซอร์สและโค้ดของบุคคลที่สาม',[`หาก release ใดรวมซอฟต์แวร์ของบุคคลที่สามหรือ open-source ให้ใบอนุญาตต้นทางและข้อความแจ้งที่จำเป็นเป็นตัวควบคุม component นั้น Proprietary License ของ Little Ganesha Tarot ไม่ลบสิทธิ์ที่ใบอนุญาตบุคคลที่สามให้ไว้โดยชอบ`,`เมื่อจำเป็น อาจมีไฟล์ license หรือ attribution เพิ่มเติมแนบมากับซอร์สหรือ release หากประกาศต้นทางขัดกับข้อความทั่วไปในหน้านี้ ให้ใบอนุญาตต้นทางมีผลสำหรับ component นั้น`]],
        ['8. ไม่มีการรับรองโดยนัย',[`ความเข้ากันได้ การอ้างถึงข้อเท็จจริง หรือการใช้ทางเทคนิคไม่ได้สร้างความสัมพันธ์ด้านการรับรอง เว้นแต่ Benedict Interactive จะประกาศ partnership อย่างชัดเจนผ่านช่องทางทางการ ผู้ใช้ไม่ควรตีความว่าบุคคลที่สามที่ถูกเอ่ยชื่อเป็นผู้สนับสนุน รับรอง หรือให้การรับรองผลิตภัณฑ์`]]
      ]},
      hi:{title:'थर्ड-पार्टी नोटिस',subtitle:'App में उपयोग या संदर्भित external technologies, services, marks और public-domain foundations।',sections:[
        ['1. इस notice का उद्देश्य',[`Little Ganesha Tarot technologies, fonts, platforms, payment rails, traditional tarot material और अन्य third-party elements का उपयोग या संदर्भ कर सकता है। वे अपने respective owners के rights, licences, terms और policies के अधीन रहते हैं।`,`यह notice third-party rights Benedict Interactive को transfer नहीं करता। किसी third party का नाम लेना sponsorship, endorsement, partnership या affiliation नहीं दर्शाता जब तक साफ़ तौर पर ऐसा न कहा जाए।`]],
        ['2. Google Fonts और typefaces',[`Current interface Google Fonts infrastructure से Cormorant Garamond, Noto Sans Thai, Noto Serif Thai, Noto Sans Devanagari और Noto Serif Devanagari request करता है। Typeface/font files अपने upstream licences और notices के अधीन रहते हैं।`,`जहाँ कोई font SIL Open Font License या किसी अन्य open-font licence के तहत distributed है, वही licence font पर लागू होगा—Little Ganesha proprietary licence नहीं। Google Fonts/Google अपने respective owner के marks/services हैं।`]],
        ['3. PromptPay और Thai QR Payment',[`PromptPay, Thai QR Payment, participating banks/payment infrastructure और संबंधित names/logos/marks अपने respective owners/operators के हैं या उनके द्वारा administered हैं। Little Ganesha Tarot voluntary support destination के रूप में recipient QR दिखाता है; यह bank, payment processor या PromptPay operator नहीं है।`,`Payment relationship user और संबंधित banking/payment services के बीच है। Payment mark या compatibility reference दिखना sponsorship/endorsement नहीं दर्शाता।`]],
        ['4. Buy Me a Coffee',[`Buy Me a Coffee current product में planned international support channel के रूप में referenced है और official Benedict Interactive destination configured होने तक active नहीं है। Buy Me a Coffee और उसके marks/services अपने owner के हैं और use होने पर provider की terms लागू होंगी।`]],
        ['5. Browsers, operating systems और device platforms',[`Browser, operating-system, app install, share sheet, storage, screenshot या अन्य platform capability का reference interoperability बताने के लिए है। Platform names/marks respective owners के हैं; availability और behaviour user platform पर निर्भर करते हैं।`]],
        ['6. Tarot history, terminology और public-domain foundations',[`Traditional tarot concepts, historical facts, conventional card names/structures और public-domain material पर Benedict Interactive exclusive ownership दावा नहीं करता। Proprietary claims केवल protectable original code, text, artwork, selection, arrangement, editing, presentation और अन्य original expression पर लागू हैं।`]],
        ['7. Open-source और third-party code',[`किसी release में third-party/open-source software शामिल होने पर उसका upstream licence और required notice उस component को govern करता है। Little Ganesha proprietary licence valid third-party licence से मिले rights को cancel नहीं करता।`,`जहाँ जरूरी हो, additional licence/attribution files source या release package के साथ दिए जा सकते हैं। General statement और upstream notice में conflict हो तो उस component के लिए upstream licence control करेगा।`]],
        ['8. No implied endorsement',[`Compatibility, factual reference या technical use endorsement relationship नहीं बनाता। Official Benedict Interactive channel से partnership स्पष्ट रूप से announce न हो तो named third party से sponsorship, certification या approval infer न करें।`]]
      ]}
    }
  };

  function normalizeLanguage(value) {
    const raw = String(value || '').toLowerCase();
    if (raw.startsWith('th')) return 'th';
    if (raw.startsWith('hi')) return 'hi';
    return 'en';
  }

  function copy(language) { return SHARED[normalizeLanguage(language)]; }
  function documentFor(id, language) {
    const key = Object.prototype.hasOwnProperty.call(DOCS, id) ? id : 'copyright';
    return DOCS[key][normalizeLanguage(language)];
  }

  window.LGTLegalContent = Object.freeze({
    version: VERSION,
    legalVersion: LEGAL_VERSION,
    effectiveDate: EFFECTIVE_DATE,
    updatedDate: LAST_UPDATED,
    defaultDocument: 'copyright',
    documentIds: Object.freeze(['copyright','terms','privacy','thirdParty']),
    language: normalizeLanguage,
    copy,
    document: documentFor
  });
})();
